## Cross-language conformance runner — reads the shared JSON specs and drives the GDScript engine.
##
## tests/*.json is the contract: the same input, the same expected output, for all four runtimes.
## The TypeScript runner is the reference this one is written against. A behaviour that only holds
## in one runtime is a divergence waiting to be found by a player.
##
## The specs are generated by tests/generate-specs.py, not written by hand.
extends SceneTree

var _passed: int = 0
var _failed: int = 0
var _total: int = 0

func _init() -> void:
	_run_flow_tests("test-cases.json")
	_run_flow_tests("test-port-routing.json")
	_run_validation_tests("test-init-validation.json")

	# ── Native tests (unit + integration) ──
	for suite_path in [
		"res://tests/test_condition_evaluator.gd",
		"res://tests/test_on_resolve_condition.gd",
		"res://tests/test_robustness.gd",
		"res://tests/test_router.gd",
		"res://tests/test_in_port_per_character.gd",
		"res://tests/test_handler_tiers.gd",
		"res://tests/test_track_info.gd",
		"res://tests/test_validation_hook.gd",
		"res://tests/test_engine_facade.gd",
		"res://tests/test_lsde_utils.gd",
	]:
		var suite: RefCounted = load(suite_path).new()
		var result: Dictionary = suite.run()
		_passed += result["passed"]
		_failed += result["failed"]
		_total += result["total"]

	print("\n━━━ Results ━━━")
	print("Total: %d | Passed: %d | Failed: %d" % [_total, _passed, _failed])
	if _failed > 0:
		print("FAIL")
	else:
		print("ALL PASSED")
	quit(_failed)

# ─── Helpers ──────────────────────────────────────────────────────────────

func _load_test_file(filename: String) -> Dictionary:
	var path: String = "res://../../tests/" + filename
	if not FileAccess.file_exists(path):
		path = "res://tests/" + filename
	if not FileAccess.file_exists(path):
		var base: String = ProjectSettings.globalize_path("res://")
		path = base.path_join("../../tests/" + filename)
	var file: FileAccess = FileAccess.open(path, FileAccess.READ)
	if file == null:
		var abs_path: String = ProjectSettings.globalize_path("res://").get_base_dir().get_base_dir().path_join("tests/" + filename)
		file = FileAccess.open(abs_path, FileAccess.READ)
	assert(file != null, "Cannot open test file: " + filename)
	var json: Variant = JSON.parse_string(file.get_as_text())
	assert(json is Dictionary, "Failed to parse: " + filename)
	return json

## The game's answer to one comparison, from the suite's stateBridge.
##
## A test on the reserved "choice" dictionary never gets here — the engine answers those from the
## history it kept during the scene.
func _make_resolver(suite: Dictionary) -> Callable:
	var answers: Dictionary = {}
	var bridge: Variant = suite.get("stateBridge")
	if bridge is Dictionary and bridge.has("conditions"):
		answers = bridge["conditions"]

	return func(test: Dictionary) -> bool:
		var key: String = "%s.%s" % [test.get("dict", ""), test.get("entry", "")]
		var answer: bool = answers[key] if answers.has(key) else true
		return not answer if test.get("op", "") == LsdeTypes.OP_NOT_EQUALS else answer

func _execute_action(action: Variant, context: Variant, next_fn: Callable) -> void:
	if action == null:
		return
	match action.get("type", ""):
		"next":
			next_fn.call()
		"selectChoice":
			context.select_choice(action.get("optionId", ""))
			next_fn.call()
		"resolveCondition":
			context.resolve(action.get("port", LsdeTypes.PORT_OUT))
			next_fn.call()
		"resolveAction":
			context.resolve()
			next_fn.call()
		"rejectAction":
			context.reject(action.get("error", "test error"))
			next_fn.call()
		"resolveCharacterPort":
			context.resolve_character_port(action.get("cardId", ""))
			next_fn.call()

## What the suite hands to init(): one payload, or the files of a per-scene export.
func _options_of(suite: Dictionary) -> Dictionary:
	if suite.has("blueprintFiles"):
		return {"files": suite["blueprintFiles"]}
	return {"data": suite["blueprint"]}

func _assert_eq(actual: Variant, expected: Variant, msg: String) -> bool:
	if actual != expected:
		print("  FAIL: %s — expected %s, got %s" % [msg, str(expected), str(actual)])
		return false
	return true

# ─── Flow tests ───────────────────────────────────────────────────────────

func _run_flow_tests(filename: String) -> void:
	var test_file: Dictionary = _load_test_file(filename)
	for suite in test_file.get("suites", []):
		for tc in suite.get("cases", []):
			_total += 1
			var display_name: String = "%s/%s" % [suite["id"], tc["id"]]
			if _run_single_flow_test(suite, tc, display_name):
				_passed += 1
				print("  PASS: %s" % display_name)
			else:
				_failed += 1

func _run_single_flow_test(suite: Dictionary, tc: Dictionary, display_name: String) -> bool:
	var engine: LsdeDialogueEngine = LsdeDialogueEngine.new()
	var report: Dictionary = engine.init(_options_of(suite))
	if report["errors"].size() > 0:
		print("  FAIL: %s — init errors: %s" % [display_name, str(report["errors"])])
		return false

	engine.set_locale(suite.get("locale", "en"))
	engine.on_resolve_condition(_make_resolver(suite))

	var steps: Array = tc.get("steps", [])
	var state: Array = [0, 0]  # [step_index, cleanup_calls]
	var failures: Array = []

	# One handler per block type, consuming the steps in order. A block that is not the next
	# expected step still reaches here — an async track, or a block the spec does not assert on —
	# and simply advances.
	var dispatch: Callable = func(block_type: String, args: Dictionary) -> Callable:
		var block: Dictionary = args["block"]
		var context: Variant = args["context"]
		var next_fn: Callable = args["next"]

		var step: Variant = steps[state[0]] if state[0] < steps.size() else null
		var expect: Variant = step["expect"] if step != null else null
		var is_expected: bool = step != null \
			and expect["type"] == block_type \
			and (expect.get("blockId") == null or expect["blockId"] == block.get("id", ""))

		if not is_expected:
			# Conditions route themselves from the resolver; an action has to say it succeeded
			# before "then" is followed.
			if context is LsdeBlockContext.ActionContext:
				context.resolve()
			next_fn.call()
			return Callable()

		if expect.get("text") != null:
			var line: Variant = block.get("text", {}).get(suite.get("locale", "en"))
			if line != expect["text"]:
				failures.append("text expected %s, got %s" % [str(expect["text"]), str(line)])

		if expect.get("visibleOptionCount") != null:
			var offered: int = 0
			for option in context.options:
				if option.get("visible") != false:
					offered += 1
			if offered != expect["visibleOptionCount"]:
				failures.append("visibleOptionCount expected %d, got %d" % [expect["visibleOptionCount"], offered])

		if expect.get("characterId") != null:
			var character: Variant = context.character
			var character_id: Variant = character.get("id") if character != null else null
			if character_id != expect["characterId"]:
				failures.append("characterId expected %s, got %s" % [str(expect["characterId"]), str(character_id)])

		state[0] += 1
		_execute_action(step.get("action"), context, next_fn)
		return func() -> void: state[1] += 1

	engine.on_dialog(func(args: Dictionary) -> Callable: return dispatch.call(LsdeTypes.BLOCK_DIALOG, args))
	engine.on_choice(func(args: Dictionary) -> Callable: return dispatch.call(LsdeTypes.BLOCK_CHOICE, args))
	engine.on_condition(func(args: Dictionary) -> Callable: return dispatch.call(LsdeTypes.BLOCK_CONDITION, args))
	engine.on_action(func(args: Dictionary) -> Callable: return dispatch.call(LsdeTypes.BLOCK_ACTION, args))

	var handle: LsdeSceneHandle = engine.scene(suite.get("sceneId", ""))
	handle.start()

	var ok: bool = true

	for failure in failures:
		print("  FAIL: %s — %s" % [display_name, failure])
		ok = false

	# Every step the spec described must have been reached.
	if not _assert_eq(state[0], steps.size(), display_name + " steps consumed"):
		ok = false

	# A block parked on waitForBlocks leaves the scene alive: it is waiting, not finished. Every
	# other suite ends, so the field defaults to false.
	var expected_running: bool = tc.get("expectedRunning", false)
	if handle.is_running() != expected_running:
		print("  FAIL: %s — scene running=%s, expected %s" % [display_name, handle.is_running(), expected_running])
		ok = false

	if tc.has("expectedVisited"):
		var visited: Array = handle.get_visited_blocks()
		var expected: Array = tc["expectedVisited"]
		if tc.get("orderIndependent", false):
			var v_sorted: Array = visited.duplicate()
			v_sorted.sort()
			var e_sorted: Array = expected.duplicate()
			e_sorted.sort()
			if not _assert_eq(v_sorted, e_sorted, display_name + " visited (order-independent)"):
				ok = false
		elif not _assert_eq(visited, expected, display_name + " visited"):
			ok = false

	if tc.has("expectedCleanupCalls"):
		if not _assert_eq(state[1], tc["expectedCleanupCalls"], display_name + " cleanup calls"):
			ok = false

	return ok

# ─── Validation tests ─────────────────────────────────────────────────────

func _run_validation_tests(filename: String) -> void:
	var test_file: Dictionary = _load_test_file(filename)
	for suite in test_file.get("suites", []):
		for tc in suite.get("cases", []):
			_total += 1
			var display_name: String = "%s/%s" % [suite["id"], tc["id"]]
			if _run_single_validation_test(suite, tc, display_name):
				_passed += 1
				print("  PASS: %s" % display_name)
			else:
				_failed += 1

func _run_single_validation_test(suite: Dictionary, tc: Dictionary, display_name: String) -> bool:
	var engine: LsdeDialogueEngine = LsdeDialogueEngine.new()
	var report: Dictionary = engine.init(_options_of(suite))
	var ok: bool = true

	var codes_of: Callable = func(entries: Array) -> Array:
		var codes: Array = []
		for entry in entries:
			codes.append(entry.get("code", ""))
		return codes

	if tc.has("expectedErrors"):
		var codes: Array = codes_of.call(report["errors"])
		var expected: Array = tc["expectedErrors"]
		if expected.is_empty():
			if not codes.is_empty():
				print("  FAIL: %s — expected no error, got %s" % [display_name, str(codes)])
				ok = false
		else:
			for code in expected:
				if not codes.has(code):
					print("  FAIL: %s — missing error %s (got %s)" % [display_name, code, str(codes)])
					ok = false

	if tc.has("expectedWarnings"):
		var codes: Array = codes_of.call(report["warnings"])
		var expected: Array = tc["expectedWarnings"]
		if expected.is_empty():
			if not codes.is_empty():
				print("  FAIL: %s — expected no warning, got %s" % [display_name, str(codes)])
				ok = false
		else:
			for code in expected:
				if not codes.has(code):
					print("  FAIL: %s — missing warning %s (got %s)" % [display_name, code, str(codes)])
					ok = false

	if tc.has("expectedStats"):
		var expected: Dictionary = tc["expectedStats"]
		var stats: Dictionary = report["stats"]
		for key in ["sceneCount", "blockCount", "connectionCount"]:
			if not _assert_eq(stats[key], expected[key], "%s %s" % [display_name, key]):
				ok = false

	return ok
