// Cross-language conformance runner — reads the shared JSON specs and drives the TS engine.
//
// `tests/*.json` is the contract: the same input, the same expected output, for all four runtimes.
// C#, C++ and GDScript each implement an equivalent runner, and this one is the reference they are
// written against. A behaviour that only holds here is a divergence waiting to be found by a
// player, so anything that changes port resolution or condition evaluation goes: TS behaviour and
// its exhaustive tests first, then this shared spec, then the three ports.
//
// The specs are generated by `tests/generate-specs.py`, not written by hand.

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { DialogueEngine } from './engine.js';
import type {
	Blueprints, ConditionTest, SceneContext,
	DialogContext, ChoiceContext, ConditionContext, ActionContext,
} from './types.js';

// ─── The shape of a spec file ───────────────────────────────────────────────

interface SpecFile {
	version: string;
	description: string;
	suites: Suite[];
}

interface Suite {
	id: string;
	description: string;
	/** One payload. Absent when the suite loads several files instead. */
	blueprint?: Blueprints;
	/** The files of a per-scene export, handed to `init()` as a list. Replaces `blueprint`. */
	blueprintFiles?: Blueprints[];
	/** The scene to play — a path or the stable id. Absent in the validation specs. */
	sceneId?: string;
	locale?: string;
	stateBridge?: {
		/** What the game answers, keyed `<dict>.<entry>`. Absent means everything is true. */
		conditions?: Record<string, boolean>;
		/**
		 * Keys answered true this many times, then false — a counter a loop can run out of. It
		 * outranks `conditions` for the same key.
		 */
		trueTimes?: Record<string, number>;
	};
	/** The suite throws from a handler. GDScript has no exceptions, and its runner skips it. */
	requiresExceptions?: boolean;
	cases: Case[];
}

interface Case {
	id: string;
	description?: string;
	steps?: Step[];
	expectedVisited?: string[];
	expectedCleanupCalls?: number;
	/** Is the scene still running when the steps are done? A block waiting for the game is. */
	expectedRunning?: boolean;
	/** What `onSceneExit` is told, once. Absent means the reason is not checked. */
	expectedExitReason?: string;
	/** With `deadlocked`: the blocks still awaited, in the order the engine reports them. */
	expectedWaitingFor?: string[];
	/** With `faulted`: the message of the error `onSceneExit` is handed. */
	expectedExitError?: string;
	/** Does an exception come out of `start()`? Absent means it must not. */
	expectedThrow?: boolean;
	/** What the handle answers to `getSceneId()` / `getScenePath()`. */
	expectedSceneId?: string;
	expectedScenePath?: string;
	orderIndependent?: boolean;
	// Validation only
	expectedErrors?: string[];
	expectedWarnings?: string[];
	expectedStats?: { sceneCount: number; blockCount: number; connectionCount: number };
	/**
	 * Where every error and warning of the case points. Each field given must match on every one of
	 * them: `sceneId` is the stable id, `scenePath` the path.
	 */
	expectedAt?: { sceneId?: string; scenePath?: string; blockId?: string };
}

interface Step {
	expect: {
		/** A v2 block type, lowercase. */
		type: string;
		blockId?: string;
		text?: string;
		visibleOptionCount?: number;
		/** The card id `context.character` must carry — what `inPortPerCharacter` is about. */
		characterId?: string;
	};
	action?: {
		type: 'next' | 'selectChoice' | 'resolveCondition' | 'resolveAction' | 'rejectAction' | 'resolveCharacterPort' | 'throw';
		/** selectChoice — the option id, which is also its exit port. */
		optionId?: string;
		/** resolveCondition — a PORT NAME (`out`, `default`, `K1`), never a boolean. */
		port?: string;
		/** resolveCharacterPort — the CARD ID (`var1`), never an index. */
		cardId?: string;
		error?: string;
	};
}

type AnyContext = DialogContext | ChoiceContext | ConditionContext | ActionContext;
type NextFn = () => void;

// ─── Helpers ────────────────────────────────────────────────────────────────

const __dirname = dirname( fileURLToPath( import.meta.url ) );
const testsDir = resolve( __dirname, '../../tests' );

function loadSpec( filename: string ): SpecFile {
	return JSON.parse( readFileSync( resolve( testsDir, filename ), 'utf-8' ) ) as SpecFile;
}

/** What the suite hands to `init()`: one payload, or the files of a per-scene export. */
function payloadOf( suite: Suite ): Blueprints | Blueprints[] {
	return suite.blueprintFiles ?? suite.blueprint!;
}

/**
 * The game's answer to one comparison, from the suite's `stateBridge`.
 *
 * A test on the reserved `choice` dictionary never gets here — the engine answers those from the
 * history it kept during the scene.
 */
function makeResolver( suite: Suite ): ( test: ConditionTest ) => boolean {
	const answers = suite.stateBridge?.conditions ?? {};
	const remaining = { ...( suite.stateBridge?.trueTimes ?? {} ) };
	return ( test ) => {
		const key = `${ test.dict }.${ test.entry }`;
		let answer: boolean;
		if ( key in remaining ) {
			answer = remaining[key]! > 0;
			remaining[key]!--;
		} else {
			answer = key in answers ? answers[key]! : true;
		}
		return test.op === 'notEquals' ? !answer : answer;
	};
}

function executeAction( step: Step, context: AnyContext, next: NextFn ): void {
	const action = step.action;
	if ( !action ) return;

	switch ( action.type ) {
		case 'next':
			next();
			break;
		case 'selectChoice':
			( context as ChoiceContext ).selectChoice( action.optionId! );
			next();
			break;
		case 'resolveCondition':
			( context as ConditionContext ).resolve( action.port! );
			next();
			break;
		case 'resolveAction':
			( context as ActionContext ).resolve();
			next();
			break;
		case 'rejectAction':
			( context as ActionContext ).reject( action.error ?? 'test error' );
			next();
			break;
		case 'resolveCharacterPort':
			( context as DialogContext ).resolveCharacterPort( action.cardId! );
			next();
			break;
		case 'throw':
			throw new Error( action.error ?? 'thrown by the spec' );
	}
}

// ─── Flow runner ────────────────────────────────────────────────────────────

function runFlowSpec( filename: string ): void {
	const spec = loadSpec( filename );

	describe( filename, () => {
		for ( const suite of spec.suites ) {
			describe( `${ suite.id } — ${ suite.description }`, () => {
				for ( const tc of suite.cases ) {
					it( tc.id + ( tc.description ? ` — ${ tc.description }` : '' ), () => {
						const engine = new DialogueEngine();
						const report = engine.init( { data: payloadOf( suite ) } );
						expect( report.errors ).toEqual( [] );

						engine.setLocale( suite.locale ?? 'en' );
						engine.onResolveCondition( makeResolver( suite ) );

						const steps = tc.steps ?? [];
						let stepIndex = 0;
						let cleanupCalls = 0;
						const exits: SceneContext[] = [];
						engine.onSceneExit( ( { context } ) => { exits.push( context ); } );

						/**
						 * One handler per block type, consuming the steps in order.
						 *
						 * A block that is not the next expected step still reaches here — an async
						 * track, or a block the spec does not assert on — and simply advances.
						 */
						const makeHandler = ( blockType: string ) =>
							( { block, context, next }: { block: { id: string }; context: AnyContext; next: NextFn } ) => {
								const step = steps[stepIndex];
								const isExpected = step
									&& step.expect.type === blockType
									&& ( !step.expect.blockId || step.expect.blockId === block.id );

								if ( !isExpected ) {
									// Auto-advance. Conditions route themselves from the resolver, and
									// an action has to say it succeeded before `then` is followed.
									if ( blockType === 'action' ) ( context as ActionContext ).resolve();
									next();
									return;
								}

								if ( step.expect.text !== undefined ) {
									const text = ( block as { text?: Record<string, string> } ).text;
									expect( text?.[suite.locale ?? 'en'] ).toBe( step.expect.text );
								}

								if ( step.expect.visibleOptionCount !== undefined ) {
									const offered = ( context as ChoiceContext ).options
										.filter( o => o.visible !== false );
									expect( offered ).toHaveLength( step.expect.visibleOptionCount );
								}

								if ( step.expect.characterId !== undefined ) {
									expect( context.character?.id ).toBe( step.expect.characterId );
								}

								stepIndex++;
								executeAction( step, context, next );
								return () => { cleanupCalls++; };
							};

						engine.onDialog( makeHandler( 'dialog' ) );
						engine.onChoice( makeHandler( 'choice' ) );
						engine.onCondition( makeHandler( 'condition' ) );
						engine.onAction( makeHandler( 'action' ) );

						const handle = engine.scene( suite.sceneId! );

						// A fault reaches whoever called start() — once the scene is closed. Caught
						// here so that everything after it can be checked, not only that it threw.
						let thrown: unknown = undefined;
						try {
							handle.start();
						} catch ( err ) {
							thrown = err ?? 'thrown';
						}
						expect( thrown !== undefined ).toBe( tc.expectedThrow === true );

						// Every step the spec described must have been reached.
						expect( stepIndex ).toBe( steps.length );
						expect( handle.isRunning() ).toBe( tc.expectedRunning === true );

						if ( tc.expectedExitReason !== undefined ) {
							expect( exits.map( e => e.reason ) ).toEqual( [tc.expectedExitReason] );
						}

						if ( tc.expectedWaitingFor !== undefined ) {
							expect( exits[0]?.waitingFor ).toEqual( tc.expectedWaitingFor );
						}

						if ( tc.expectedExitError !== undefined ) {
							expect( ( exits[0]?.error as Error | undefined )?.message ).toBe( tc.expectedExitError );
						}

						if ( tc.expectedSceneId !== undefined ) {
							expect( handle.getSceneId() ).toBe( tc.expectedSceneId );
						}

						if ( tc.expectedScenePath !== undefined ) {
							expect( handle.getScenePath() ).toBe( tc.expectedScenePath );
						}

						if ( tc.expectedVisited ) {
							const visited = Array.from( handle.getVisitedBlocks() );
							if ( tc.orderIndependent ) {
								expect( visited.sort() ).toEqual( [...tc.expectedVisited].sort() );
							} else {
								expect( visited ).toEqual( tc.expectedVisited );
							}
						}

						if ( tc.expectedCleanupCalls !== undefined ) {
							expect( cleanupCalls ).toBe( tc.expectedCleanupCalls );
						}
					} );
				}
			} );
		}
	} );
}

// ─── Validation runner ──────────────────────────────────────────────────────

function runValidationSpec( filename: string ): void {
	const spec = loadSpec( filename );

	describe( filename, () => {
		for ( const suite of spec.suites ) {
			describe( `${ suite.id } — ${ suite.description }`, () => {
				for ( const tc of suite.cases ) {
					it( tc.id + ( tc.description ? ` — ${ tc.description }` : '' ), () => {
						const report = new DialogueEngine().init( { data: payloadOf( suite ) } );

						// Compared WHOLE, order aside. Checking only that each listed code was present let a
						// runtime add a code the spec does not list, unnoticed. The order is left out on
						// purpose: in C++ a PropertyBag is an unordered_map, so two warnings about one call
						// may come in either order.
						if ( tc.expectedErrors ) {
							expect( report.errors.map( e => e.code ).sort() ).toEqual( [...tc.expectedErrors].sort() );
						}

						if ( tc.expectedWarnings ) {
							expect( report.warnings.map( w => w.code ).sort() ).toEqual( [...tc.expectedWarnings].sort() );
						}

						if ( tc.expectedAt ) {
							for ( const entry of [...report.errors, ...report.warnings] ) {
								for ( const [field, value] of Object.entries( tc.expectedAt ) ) {
									const actual = entry[field as 'sceneId' | 'scenePath' | 'blockId'];
									expect( actual, `${ entry.code } ${ field }` ).toBe( value );
								}
							}
						}

						if ( tc.expectedStats ) {
							expect( report.stats ).toEqual( tc.expectedStats );
						}
					} );
				}
			} );
		}
	} );
}

// ─── Execute ────────────────────────────────────────────────────────────────

runFlowSpec( 'test-cases.json' );
runFlowSpec( 'test-port-routing.json' );
runValidationSpec( 'test-init-validation.json' );
