// LSDE Dialog Engine — Public barrel export
// Build order: types → validator → graph → condition-evaluator → port-resolver
//              → handler-registry → block-context → track → scene-handle → engine

export { DialogueEngine } from './engine.js';
export { LsdeUtils } from './lsde-utils.js';

// The payload contract, generated by LSDE and re-exported whole: `Blueprints`, `Scene`, `Block`,
// `Link`, `Option`, `ConditionTest`, `ConditionCase`, `ActionCall`, `Card`, the enum objects
// (`BlockType`, `ConditionOperator`, `ConditionJoin`, `ValueType`, `LiteralValueType`, `CardRole`)
// and `Ports`. A game imports them from here rather than from the file its own export wrote.
export * from './blueprint-types.js';

export { NATIVE_PROPERTY_IDS, SceneEndReason } from './types.js';
export type { LocaleTable } from './lsde-utils.js';
// The evaluator a game hands to LsdeUtils.evaluateConditionCases / evaluateEachCase. Without
// it there is no name for the function the caller has to write.
export type { ConditionEvaluator } from './condition-evaluator.js';

export type {
	// The engine's names for the payload types, plus what it adds on top
	BlueprintExport, BlueprintScene, BlueprintBlock, BlueprintConnection, BlockOfType,
	DialogBlock, ChoiceBlock, ConditionBlock, RouterBlock, ActionBlock, NoteBlock,
	RuntimeChoiceItem, RuntimeConditionCase, NativeProperties,

	// Engine types
	DiagnosticReport, DiagnosticEntry, DiagnosticStats,
	InitOptions, CheckOptions,
	ValidationResult, CleanupFn, TrackInfo,

	// Context types
	BaseBlockContext, DialogContext, ChoiceContext, ConditionContext, RouterContext, ActionContext,
	BeforeBlockContext, SceneContext,

	// Handler types
	BlockHandlerArgs, BlockHandler,
	DialogHandler, ChoiceHandler, ConditionHandler, ActionHandler,
	ValidateNextBlockArgs, ValidateNextBlockContext, ValidateNextBlockHandler,
	InvalidateBlockArgs, InvalidateBlockHandler,
	BeforeBlockArgs, BeforeBlockHandler,
	SceneLifecycleArgs, SceneLifecycleHandler,

	// Scene handle & engine interface
	SceneHandle,
	IDialogueEngine,

	// Port resolution
	PortResolutionInput, PortResolutionResult,
} from './types.js';
