// The shape of the shared conformance specs in tests/*.json.
//
// Those files are the contract every runtime must pass: the same input, the same expected output,
// in TypeScript, C#, C++ and GDScript. They are generated by tests/generate-specs.py — never
// written by hand — so the four runtimes cannot drift on the shape of a payload.

using System.Collections.Generic;

namespace LsdeDialogEngine.Tests
{
    public class TestFile
    {
        public string Version { get; set; } = "";
        public string Description { get; set; } = "";
        public List<TestSuite> Suites { get; set; } = new();
    }

    public class TestSuite
    {
        public string Id { get; set; } = "";
        public string Description { get; set; } = "";
        public BlueprintExport Blueprint { get; set; } = new();

        /// <summary>The scene to play — a path or the stable id. Absent in the validation specs.</summary>
        public string? SceneId { get; set; }

        public string? Locale { get; set; }

        /// <summary>What the game answers, keyed "&lt;dict&gt;.&lt;entry&gt;". Absent means everything is true.</summary>
        public StateBridgeConfig? StateBridge { get; set; }

        public List<TestCase> Cases { get; set; } = new();
    }

    public class StateBridgeConfig
    {
        public Dictionary<string, bool>? Conditions { get; set; }
    }

    public class TestCase
    {
        public string Id { get; set; } = "";
        public string? Description { get; set; }
        public List<TestStep>? Steps { get; set; }
        public List<string>? ExpectedVisited { get; set; }
        public int? ExpectedCleanupCalls { get; set; }

        /// <summary>Is the scene still running when the steps are done?</summary>
        /// <remarks>A block parked on WaitForBlocks leaves the scene alive: it is waiting, not
        /// finished. Every other suite ends, so this defaults to false.</remarks>
        public bool? ExpectedRunning { get; set; }
        public bool? OrderIndependent { get; set; }

        // Validation only
        public List<string>? ExpectedErrors { get; set; }
        public List<string>? ExpectedWarnings { get; set; }
        public ExpectedStats? ExpectedStats { get; set; }
    }

    public class ExpectedStats
    {
        public int SceneCount { get; set; }
        public int BlockCount { get; set; }
        public int ConnectionCount { get; set; }
    }

    public class TestStep
    {
        public StepExpect Expect { get; set; } = new();
        public StepAction? Action { get; set; }
    }

    public class StepExpect
    {
        /// <summary>A v2 block type, LOWERCASE.</summary>
        public string Type { get; set; } = "";

        public string? BlockId { get; set; }
        public string? Text { get; set; }
        public int? VisibleOptionCount { get; set; }
    }

    public class StepAction
    {
        /// <summary>next, selectChoice, resolveCondition, resolveAction, rejectAction, resolveCharacterPort.</summary>
        public string Type { get; set; } = "";

        /// <summary>selectChoice — the option id, which is also its exit port.</summary>
        public string? OptionId { get; set; }

        /// <summary>resolveCondition — a PORT NAME ("out", "default", "K1"), never a boolean.</summary>
        public string? Port { get; set; }

        /// <summary>resolveCharacterPort — the CARD ID (var1), never an index.</summary>
        public string? CardId { get; set; }

        public string? Error { get; set; }
    }
}
