#pragma once
// Auto-generated by LSDE — do not edit manually.
// 6 keys.

namespace EngineConformanceScene {

/** @example Continue */
inline constexpr const char* uiCommonContinue = "ui.common.continue";

/** @example No */
inline constexpr const char* uiCommonNo = "ui.common.no";

/** @example Yes */
inline constexpr const char* uiCommonYes = "ui.common.yes";

/** @example Welcome aboard. */
inline constexpr const char* uiCrewGreeting = "ui.crew.greeting";

/** @example Airlock 4 */
inline constexpr const char* uiHudAirlockLabel = "ui.hud.airlock_label";

/** @example {{count}} plasma cells */
inline constexpr const char* uiInventoryCell = "ui.inventory.cell";

}  // namespace EngineConformanceScene
