# Auto-generated by LSDE — do not edit manually.
# 6 keys.

class_name EngineConformanceScene

## @example Continue
const uiCommonContinue = "ui.common.continue"

## @example No
const uiCommonNo = "ui.common.no"

## @example Yes
const uiCommonYes = "ui.common.yes"

## @example Welcome aboard.
const uiCrewGreeting = "ui.crew.greeting"

## @example Airlock 4
const uiHudAirlockLabel = "ui.hud.airlock_label"

## @example {{count}} plasma cells
const uiInventoryCell = "ui.inventory.cell"
