// Auto-generated by LSDE — do not edit manually.
// 6 keys.

public static class EngineConformanceScene
{
    /// <summary>
    /// <para>@example Continue</para>
    /// </summary>
    public const string uiCommonContinue = "ui.common.continue";

    /// <summary>
    /// <para>@example No</para>
    /// </summary>
    public const string uiCommonNo = "ui.common.no";

    /// <summary>
    /// <para>@example Yes</para>
    /// </summary>
    public const string uiCommonYes = "ui.common.yes";

    /// <summary>
    /// <para>@example Welcome aboard.</para>
    /// </summary>
    public const string uiCrewGreeting = "ui.crew.greeting";

    /// <summary>
    /// <para>@example Airlock 4</para>
    /// </summary>
    public const string uiHudAirlockLabel = "ui.hud.airlock_label";

    /// <summary>
    /// <para>@example {{count}} plasma cells</para>
    /// </summary>
    public const string uiInventoryCell = "ui.inventory.cell";
}
