// Auto-generated by LSDE — do not edit manually.
// 6 keys.

export const EngineConformanceScene = {
	/** @example Continue */
	uiCommonContinue: "ui.common.continue",

	/** @example No */
	uiCommonNo: "ui.common.no",

	/** @example Yes */
	uiCommonYes: "ui.common.yes",

	/** @example Welcome aboard. */
	uiCrewGreeting: "ui.crew.greeting",

	/** @example Airlock 4 */
	uiHudAirlockLabel: "ui.hud.airlock_label",

	/** @example {{count}} plasma cells */
	uiInventoryCell: "ui.inventory.cell",
} as const;

export type EngineConformanceSceneIdentifier = keyof typeof EngineConformanceScene;
export type EngineConformanceScenePath = (typeof EngineConformanceScene)[EngineConformanceSceneIdentifier];
