// The shape of the shared conformance specs in tests/*.json.
//
// Those files are the contract every runtime must pass: the same input, the same expected output,
// in TypeScript, C#, C++ and GDScript. They are generated by tests/generate-specs.py — never
// written by hand — so the four runtimes cannot drift on the shape of a payload.

#pragma once

#include <lsde/types.h>
#include <string>
#include <vector>
#include <optional>
#include <unordered_map>

namespace lsde::tests {

struct StateBridgeConfig {
    /// What the game answers, keyed "<dict>.<entry>". Absent means everything is true.
    std::unordered_map<std::string, bool> conditions;
};

struct StepExpect {
    /// A v2 block type, LOWERCASE.
    std::string type;
    std::optional<std::string> blockId;
    std::optional<std::string> text;
    std::optional<int> visibleOptionCount;
    /// The card id context->character() must carry — what inPortPerCharacter is about.
    std::optional<std::string> characterId;
};

struct StepAction {
    /// next, selectChoice, resolveCondition, resolveAction, rejectAction, resolveCharacterPort.
    std::string type;
    /// selectChoice — the option id, which is also its exit port.
    std::optional<std::string> optionId;
    /// resolveCondition — a PORT NAME ("out", "default", "K1"), never a boolean.
    std::optional<std::string> port;
    /// resolveCharacterPort — the CARD ID (var1), never an index.
    std::optional<std::string> cardId;
    std::optional<std::string> error;
};

struct TestStep {
    StepExpect expect;
    std::optional<StepAction> action;
};

struct ExpectedStats {
    int sceneCount = 0;
    int blockCount = 0;
    int connectionCount = 0;
};

struct TestCase {
    std::string id;
    std::optional<std::string> description;
    std::vector<TestStep> steps;
    std::optional<std::vector<std::string>> expectedVisited;
    std::optional<int> expectedCleanupCalls;
    /// Is the scene still running when the steps are done?
    ///
    /// A block parked on waitForBlocks leaves the scene alive: it is waiting, not finished. Every
    /// other suite ends, so this defaults to false.
    bool expectedRunning = false;
    std::optional<bool> orderIndependent;
    /// Validation only. nullopt = the spec says nothing; an empty vector = expect none.
    std::optional<std::vector<std::string>> expectedErrors;
    std::optional<std::vector<std::string>> expectedWarnings;
    std::optional<ExpectedStats> expectedStats;
};

struct TestSuite {
    std::string id;
    std::string description;
    /// One payload. Left empty when the suite loads several files instead.
    BlueprintExport blueprint;
    /// The files of a per-scene export, handed to init() as `files`. Replaces `blueprint`.
    std::optional<std::vector<BlueprintExport>> blueprintFiles;
    /// The scene to play — a path or the stable id. Absent in the validation specs.
    std::optional<std::string> sceneId;
    std::optional<std::string> locale;
    std::optional<StateBridgeConfig> stateBridge;
    std::vector<TestCase> cases;
};

struct TestFile {
    std::string version;
    std::string description;
    std::vector<TestSuite> suites;
};

} // namespace lsde::tests
