// Auto-generated by LSDE. Do not edit manually.
// The shape of Engine-Conformance-Scene.blueprints.json (format "lsde-blueprints", version 1).
// Field names follow the exporter's naming convention (asIs): they match the file exactly.
// Deserialize with Newtonsoft.Json or System.Text.Json. Unity's JsonUtility cannot read dictionaries
// (text, props, args) nor object values, so it cannot read this file.
#nullable disable

using System.Collections.Generic;

namespace EngineConformanceSceneBlueprints
{
    /// <summary>
    /// <para>What a block is. Decides which optional fields it carries.</para>
    /// </summary>
    public static class BlockType
    {
        public const string Dialog = "dialog";
        public const string Choice = "choice";
        public const string Condition = "condition";
        public const string Action = "action";
        public const string Note = "note";
    }

    /// <summary>
    /// <para>How a condition compares a dictionary entry to its value.</para>
    /// </summary>
    public static class ConditionOperator
    {
        public new const string Equals = "equals";
        public const string NotEquals = "notEquals";
        public const string LessThan = "lessThan";
        public const string LessOrEqual = "lessOrEqual";
        public const string GreaterThan = "greaterThan";
        public const string GreaterOrEqual = "greaterOrEqual";
    }

    /// <summary>
    /// <para>How a comparison links to the one above it. The list is flat: precedence is yours.</para>
    /// </summary>
    public static class ConditionJoin
    {
        public const string And = "and";
        public const string Or = "or";
    }

    /// <summary>
    /// <para>What a function parameter accepts: a literal, or a key picked in a dictionary.</para>
    /// </summary>
    public static class ValueType
    {
        public const string Boolean = "boolean";
        public const string String = "string";
        public const string Number = "number";
        public const string DictionaryKey = "dictionaryKey";
    }

    /// <summary>
    /// <para>What a dictionary stores, hence what its entries are compared to.</para>
    /// </summary>
    public static class LiteralValueType
    {
        public const string Boolean = "boolean";
        public const string String = "string";
        public const string Number = "number";
    }

    /// <summary>
    /// <para>What a card is used for in the editor.</para>
    /// </summary>
    public static class CardRole
    {
        public const string None = "none";
        public const string Characters = "characters";
        public const string Emotions = "emotions";
        public const string Places = "places";
    }

    /// <summary>
    /// <para>The ports every engine must know. Option, case and actor ports are named by the project.</para>
    /// </summary>
    public static class Ports
    {
        /// <summary>
        /// <para>The single entry port of every block.</para>
        /// </summary>
        public const string In = "in";
        /// <summary>
        /// <para>The default exit of a dialog, and the true exit of an if-style condition.</para>
        /// </summary>
        public const string Out = "out";
        /// <summary>
        /// <para>The exit of an action block once its calls succeeded.</para>
        /// </summary>
        public const string Then = "then";
        /// <summary>
        /// <para>The exit of an action block when a call failed.</para>
        /// </summary>
        public const string Catch = "catch";
        /// <summary>
        /// <para>The fallback exit of a condition block: no case matched.</para>
        /// </summary>
        public const string Default = "default";
        /// <summary>
        /// <para>NOT a port: the reserved ConditionTest.dict that reads past answers. entry is a CHOICE block id, value an Option.id of that block. The engine answers it from what it recorded during the scene; the memory starts and ends with the scene, and no project dictionary may use this id.</para>
        /// </summary>
        public const string Choice = "choice";
    }

    /// <summary>
    /// <para>Which software wrote the file, to trace a delivered payload back to its version.</para>
    /// </summary>
    public sealed class Generator
    {
        /// <summary>
        /// <para>Always LSDE.</para>
        /// </summary>
        public string app { get; set; } = "";

        /// <summary>
        /// <para>The software version, e.g. 2.0.3 - not the format version.</para>
        /// </summary>
        public string version { get; set; } = "";
    }

    /// <summary>
    /// <para>A dictionary the engine maintains, as declared in the project. Conditions cite it by id.</para>
    /// </summary>
    public sealed class DictionaryDefinition
    {
        /// <summary>
        /// <para>The dictionary id, as ConditionTest.dict cites it.</para>
        /// </summary>
        public string id { get; set; } = "";

        /// <summary>
        /// <para>What its entries are compared to.</para>
        /// </summary>
        public string valueType { get; set; } = "";

        /// <summary>
        /// <para>The entry keys, in declaration order.</para>
        /// </summary>
        public List<string> entries { get; set; } = new List<string>();
    }

    /// <summary>
    /// <para>One parameter of an engine function.</para>
    /// </summary>
    public sealed class FunctionParameter
    {
        /// <summary>
        /// <para>The argument name, as ActionCall.args keys it.</para>
        /// </summary>
        public string name { get; set; } = "";

        /// <summary>
        /// <para>What the argument holds.</para>
        /// </summary>
        public string type { get; set; } = "";

        /// <summary>
        /// <para>Only when type is dictionaryKey: where the value is picked. Absent = null or empty.</para>
        /// </summary>
        public string dictionary { get; set; }
    }

    /// <summary>
    /// <para>A function the engine implements, as ActionCall.fn names it.</para>
    /// </summary>
    public sealed class FunctionDefinition
    {
        /// <summary>
        /// <para>The function id.</para>
        /// </summary>
        public string id { get; set; } = "";

        /// <summary>
        /// <para>Its parameters, in declaration order.</para>
        /// </summary>
        public List<FunctionParameter> @params { get; set; } = new List<FunctionParameter>();
    }

    /// <summary>
    /// <para>A card cited by blocks: the other end of Block.actors and Block.emotion.</para>
    /// </summary>
    public sealed class Card
    {
        /// <summary>
        /// <para>The stable editor id (var3) that blocks reference.</para>
        /// </summary>
        public string id { get; set; } = "";

        /// <summary>
        /// <para>The name the game gives this card, never the editor label.</para>
        /// </summary>
        public string name { get; set; } = "";

        /// <summary>
        /// <para>What the card is used for.</para>
        /// </summary>
        public string role { get; set; } = "";
    }

    /// <summary>
    /// <para>An outgoing wire, seen from the block that carries it.</para>
    /// </summary>
    public sealed class Link
    {
        /// <summary>
        /// <para>The exit port: a fixed port (see Ports), an option id, a case port or an actor id.</para>
        /// </summary>
        public string port { get; set; } = "";

        /// <summary>
        /// <para>The target block id, relative to the same scene.</para>
        /// </summary>
        public string to { get; set; } = "";

        /// <summary>
        /// <para>The target's entry port, always in today.</para>
        /// </summary>
        public string toPort { get; set; } = "";
    }

    /// <summary>
    /// <para>What an action block asks the engine to run.</para>
    /// </summary>
    public sealed class ActionCall
    {
        /// <summary>
        /// <para>The function id. May be empty when the designer has not picked one yet.</para>
        /// </summary>
        public string fn { get; set; } = "";

        /// <summary>
        /// <para>The arguments BY NAME, as declared in FunctionDefinition.params.</para>
        /// </summary>
        public Dictionary<string, object> args { get; set; } = new Dictionary<string, object>();
    }

    /// <summary>
    /// <para>One comparison: a dictionary entry against a value. The reserved dict id "choice" is the exception — it reads the answers the player already gave IN THIS SCENE, which the engine tracks on its own. No project dictionary can be named that.</para>
    /// </summary>
    public sealed class ConditionTest
    {
        /// <summary>
        /// <para>The dictionary id, see DictionaryDefinition.id. "choice" is reserved: see Ports.Choice.</para>
        /// </summary>
        public string dict { get; set; } = "";

        /// <summary>
        /// <para>The entry read in that dictionary. With dict "choice", a CHOICE block id of this scene.</para>
        /// </summary>
        public string entry { get; set; } = "";

        /// <summary>
        /// <para>The comparison.</para>
        /// </summary>
        public string op { get; set; } = "";

        /// <summary>
        /// <para>The right-hand side; its type follows the dictionary's valueType. With dict "choice", the Option.id the player picked.</para>
        /// </summary>
        public object value { get; set; }

        /// <summary>
        /// <para>Link with the comparison ABOVE. Absent on the first one. Absent = null or empty.</para>
        /// </summary>
        public string join { get; set; }
    }

    /// <summary>
    /// <para>One case of a condition block: the exit port, and what must hold for it.</para>
    /// </summary>
    public sealed class ConditionCase
    {
        /// <summary>
        /// <para>The exit port of this case (K1...), or the block's out when cases share one exit.</para>
        /// </summary>
        public string port { get; set; } = "";

        /// <summary>
        /// <para>Absent = always true. Such a case makes every following case unreachable. Absent = null or empty.</para>
        /// </summary>
        public List<ConditionTest> when { get; set; } = new List<ConditionTest>();
    }

    /// <summary>
    /// <para>One answer of a choice block, a translated key in its own right.</para>
    /// </summary>
    public sealed class Option
    {
        /// <summary>
        /// <para>The option id, which is also its exit port (C1...).</para>
        /// </summary>
        public string id { get; set; } = "";

        /// <summary>
        /// <para>The full i18n key of its text.</para>
        /// </summary>
        public string key { get; set; } = "";

        /// <summary>
        /// <para>Its text by locale, when texts are exported. Absent = null or empty.</para>
        /// </summary>
        public Dictionary<string, string> text { get; set; } = new Dictionary<string, string>();

        /// <summary>
        /// <para>Absent = always offered. Absent = null or empty.</para>
        /// </summary>
        public List<ConditionTest> when { get; set; } = new List<ConditionTest>();
    }

    /// <summary>
    /// <para>A node of the graph. type decides which optional fields are present.</para>
    /// </summary>
    public sealed class Block
    {
        /// <summary>
        /// <para>Identity RELATIVE to its scene (DIALOG-002): what links and Scene.start reference.</para>
        /// </summary>
        public string id { get; set; } = "";

        /// <summary>
        /// <para>The full i18n key, as localization files carry it.</para>
        /// </summary>
        public string key { get; set; } = "";

        /// <summary>
        /// <para>The readable name (its summary), when written. Absent = null or empty.</para>
        /// </summary>
        public string label { get; set; }

        /// <summary>
        /// <para>Readable names above the block, root first. Empty ones are skipped. Absent = null or empty.</para>
        /// </summary>
        public List<string> parentLabels { get; set; } = new List<string>();

        /// <summary>
        /// <para>What the block is.</para>
        /// </summary>
        public string type { get; set; } = "";

        /// <summary>
        /// <para>Card ids of who speaks. Resolve them through Blueprints.cards. Absent = null or empty.</para>
        /// </summary>
        public List<string> actors { get; set; } = new List<string>();

        /// <summary>
        /// <para>Card id of the emotion, when one is set. Absent = null or empty.</para>
        /// </summary>
        public string emotion { get; set; }

        /// <summary>
        /// <para>Only with emotion. Absent = null or empty.</para>
        /// </summary>
        public double? intensity { get; set; }

        /// <summary>
        /// <para>The line by locale, dialogs only, when texts are exported. Absent = null or empty.</para>
        /// </summary>
        public Dictionary<string, string> text { get; set; } = new Dictionary<string, string>();

        /// <summary>
        /// <para>The body of a note block: never translated, only when notes are exported. Absent = null or empty.</para>
        /// </summary>
        public string body { get; set; }

        /// <summary>
        /// <para>The team note on the block, only when notes are exported. Absent = null or empty.</para>
        /// </summary>
        public string note { get; set; }

        /// <summary>
        /// <para>Properties SET on the block, native and project-declared alike, by id. Ids never collide: a project property cannot take a native name. One native holds a LIST rather than a scalar: waitForBlocks, an array of block ids OF THIS SCENE the block waits for before it advances - the counterpart of isAsync. Absent = null or empty.</para>
        /// </summary>
        public Dictionary<string, object> props { get; set; } = new Dictionary<string, object>();

        /// <summary>
        /// <para>Action blocks: what to run, in order. Absent = null or empty.</para>
        /// </summary>
        public List<ActionCall> calls { get; set; } = new List<ActionCall>();

        /// <summary>
        /// <para>Condition blocks: the cases, in evaluation order. Absent = null or empty.</para>
        /// </summary>
        public List<ConditionCase> cases { get; set; } = new List<ConditionCase>();

        /// <summary>
        /// <para>Choice blocks: the answers, in display order. Absent = null or empty.</para>
        /// </summary>
        public List<Option> options { get; set; } = new List<Option>();

        /// <summary>
        /// <para>Outgoing wires. Absent when nothing leaves the block. Absent = null or empty.</para>
        /// </summary>
        public List<Link> next { get; set; } = new List<Link>();
    }

    /// <summary>
    /// <para>One scene: its blocks, and where it starts.</para>
    /// </summary>
    public sealed class Scene
    {
        /// <summary>
        /// <para>The scene path without the reserved namespace (acte1, chap1.acte1).</para>
        /// </summary>
        public string scene { get; set; } = "";

        /// <summary>
        /// <para>The readable name of the scene, when written. Absent = null or empty.</para>
        /// </summary>
        public string label { get; set; }

        /// <summary>
        /// <para>The entry block id. Absent = the scene has no entry and cannot play. Absent = null or empty.</para>
        /// </summary>
        public string start { get; set; }

        /// <summary>
        /// <para>Every exported block of the scene.</para>
        /// </summary>
        public List<Block> blocks { get; set; } = new List<Block>();
    }

    /// <summary>
    /// <para>The whole file. One scene per file or all of them: the only difference between the two split modes.</para>
    /// </summary>
    public sealed class Blueprints
    {
        /// <summary>
        /// <para>Always lsde-blueprints.</para>
        /// </summary>
        public string format { get; set; } = "";

        /// <summary>
        /// <para>The FORMAT version. Bumps only when this contract changes.</para>
        /// </summary>
        public int version { get; set; }

        /// <summary>
        /// <para>Which software wrote the file.</para>
        /// </summary>
        public Generator generator { get; set; } = new Generator();

        /// <summary>
        /// <para>ISO 8601 instant of the export.</para>
        /// </summary>
        public string exportedAt { get; set; } = "";

        /// <summary>
        /// <para>The project name.</para>
        /// </summary>
        public string project { get; set; } = "";

        /// <summary>
        /// <para>Every locale of the project.</para>
        /// </summary>
        public List<string> locales { get; set; } = new List<string>();

        /// <summary>
        /// <para>The locale that is written first. Empty when the project declares none.</para>
        /// </summary>
        public string referenceLocale { get; set; } = "";

        /// <summary>
        /// <para>The declared vocabulary, whole, never trimmed to the exported scenes.</para>
        /// </summary>
        public List<DictionaryDefinition> dictionaries { get; set; } = new List<DictionaryDefinition>();

        /// <summary>
        /// <para>The declared engine functions.</para>
        /// </summary>
        public List<FunctionDefinition> functions { get; set; } = new List<FunctionDefinition>();

        /// <summary>
        /// <para>The cards that blocks may cite.</para>
        /// </summary>
        public List<Card> cards { get; set; } = new List<Card>();

        /// <summary>
        /// <para>The scenes carried by this file.</para>
        /// </summary>
        public List<Scene> scenes { get; set; } = new List<Scene>();
    }

}
