#pragma warning disable CS8981

// Auto-generated by LSDE. Do not edit manually.
// Identifiers used by Engine-Conformance-Scene.blueprints.json: scenes, blocks, options, cards, dictionaries and functions.
// Compare these constants to what the payload carries; never retype the strings.

public static class EngineConformanceSceneBlueprintIds
{
    /// <summary>
    /// <para>Every scene of the payload, by its scene path.</para>
    /// </summary>
    public static class Scenes
    {
        /// <summary>
        /// <para>@start ACTION-001</para>
        /// <para>@blocks 18</para>
        /// </summary>
        public const string reactor_breach = "reactor_breach";

        /// <summary>
        /// <para>@start DIALOG-001</para>
        /// <para>@blocks 4</para>
        /// </summary>
        public const string docking_ring_brief = "docking_ring_brief";
    }
    /// <summary>
    /// <para>Every block id, grouped by scene. Ids are relative to their scene: next.to and start use them.</para>
    /// </summary>
    public static class Blocks
    {
        /// <summary>
        /// <para>@scene reactor_breach</para>
        /// </summary>
        public static class reactor_breach
        {
            /// <summary>
            /// <para>@type note</para>
            /// <para>@note Cette note n'a pas de port d'entrée : elle ne se joue jamais.</para>
            /// <para>@key __blueprints__.reactor_breach.NOTE-001</para>
            /// </summary>
            public const string NOTE_001 = "NOTE-001";

            /// <summary>
            /// <para>@type note</para>
            /// <para>@note Deuxième note, sans aucun fil : deux notes suffisent à montrer qu'elles ne comptent pas dans le flux.</para>
            /// <para>@key __blueprints__.reactor_breach.NOTE-002</para>
            /// </summary>
            public const string NOTE_002 = "NOTE-002";

            /// <summary>
            /// <para>@type action</para>
            /// <para>@start</para>
            /// <para>@calls play_music, set_counter, write_flag</para>
            /// <para>@next then -&gt; DIALOG-002, catch -&gt; DIALOG-001</para>
            /// <para>@note Le réacteur monte depuis vingt minutes et personne n'a coupé la musique du pont.</para>
            /// <para>@key __blueprints__.reactor_breach.ACTION-001</para>
            /// </summary>
            public const string ACTION_001 = "ACTION-001";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example No sound. Of course there is no sound.</para>
            /// <para>@actors nora</para>
            /// <para>@emotion suspicious x45</para>
            /// <para>@next out -&gt; DIALOG-002</para>
            /// <para>@note Nora encaisse la panne sans s'arrêter. Elle n'a pas dormi depuis deux jours.</para>
            /// <para>@key __blueprints__.reactor_breach.DIALOG-001</para>
            /// </summary>
            public const string DIALOG_001 = "DIALOG-001";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Reactor deck.{|} The floor is warm through my boots.</para>
            /// <para>@actors nora</para>
            /// <para>@emotion neutral x20</para>
            /// <para>@next out -&gt; DIALOG-003</para>
            /// <para>@note Première réplique de la scène. Nora descend seule, avant que Kael la rattrape.</para>
            /// <para>@key __blueprints__.reactor_breach.DIALOG-002</para>
            /// </summary>
            public const string DIALOG_002 = "DIALOG-002";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Someone has been down here. Recently.</para>
            /// <para>@actors kael, nora</para>
            /// <para>@emotion afraid x60</para>
            /// <para>@next var2 -&gt; DIALOG-005, out -&gt; CHOICE-001, var1 -&gt; DIALOG-011</para>
            /// <para>@note Les deux le disent en même temps, et aucun des deux ne veut être celui qui a raison.</para>
            /// <para>@key __blueprints__.reactor_breach.DIALOG-003</para>
            /// </summary>
            public const string DIALOG_003 = "DIALOG-003";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Then tell me what I am looking at.</para>
            /// <para>@actors nora</para>
            /// <para>@emotion neutral x35</para>
            /// <para>@next out -&gt; DIALOG-012</para>
            /// <para>@note Elle ne hausse pas le ton. C'est ce qui inquiète Kael.</para>
            /// <para>@key __blueprints__.reactor_breach.DIALOG-005</para>
            /// </summary>
            public const string DIALOG_005 = "DIALOG-005";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Do not say my name out loud.</para>
            /// <para>@actors vesk</para>
            /// <para>@emotion afraid x100</para>
            /// <para>@next out -&gt; DIALOG-008</para>
            /// <para>@note Vesk se cache derrière le réservoir. Il ne parle que si le joueur l'a déjà croisé ailleurs.</para>
            /// <para>@key __blueprints__.reactor_breach.DIALOG-007</para>
            /// </summary>
            public const string DIALOG_007 = "DIALOG-007";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Everyone done? The {{i2}} is still on the panel.</para>
            /// <para>@actors nora</para>
            /// <para>@emotion neutral x25</para>
            /// <para>@next out -&gt; CHOICE-001</para>
            /// <para>@note Nora attend que les deux autres se taisent avant de reprendre la main.</para>
            /// <para>@key __blueprints__.reactor_breach.DIALOG-008</para>
            /// </summary>
            public const string DIALOG_008 = "DIALOG-008";

            /// <summary>
            /// <para>@type choice</para>
            /// <para>@actors nora</para>
            /// <para>@emotion neutral x30</para>
            /// <para>@options C1, C2, C3, C4</para>
            /// <para>@next C1 -&gt; COND-001, C2 -&gt; COND-001, C3 -&gt; ACTION-002, C4 -&gt; COND-002</para>
            /// <para>@note Le choix qui porte toute la scène : les conditions plus bas relisent ce que le joueur répond ici.</para>
            /// <para>@key __blueprints__.reactor_breach.CHOICE-001</para>
            /// </summary>
            public const string CHOICE_001 = "CHOICE-001";

            /// <summary>
            /// <para>@type condition</para>
            /// <para>@next K1 -&gt; ACTION-002, K2 -&gt; COND-003, K3 -&gt; DIALOG-009, default -&gt; COND-002</para>
            /// <para>@note Trois issues et un repli. Le troisième cas n'a aucune comparaison : il est toujours vrai.</para>
            /// <para>@key __blueprints__.reactor_breach.COND-001</para>
            /// </summary>
            public const string COND_001 = "COND-001";

            /// <summary>
            /// <para>@type condition</para>
            /// <para>@next default -&gt; DIALOG-010, out -&gt; COND-003</para>
            /// <para>@note Deux issues seulement : vrai ou repli. Trois comparaisons liées par ET puis OU.</para>
            /// <para>@key __blueprints__.reactor_breach.COND-002</para>
            /// </summary>
            public const string COND_002 = "COND-002";

            /// <summary>
            /// <para>@type condition</para>
            /// <para>@next default -&gt; DIALOG-009, out -&gt; DIALOG-010</para>
            /// <para>@note Relit ce que le joueur a répondu plus haut, sans qu'aucune variable n'ait été posée pour ça.</para>
            /// <para>@key __blueprints__.reactor_breach.COND-003</para>
            /// </summary>
            public const string COND_003 = "COND-003";

            /// <summary>
            /// <para>@type action</para>
            /// <para>@calls set_switch, add_item, shake_camera, close_bulkhead, unlock_achievement</para>
            /// <para>@next then -&gt; COND-003, catch -&gt; DIALOG-010</para>
            /// <para>@note Cinq appels d'affilée, dont un sans le moindre paramètre.</para>
            /// <para>@key __blueprints__.reactor_breach.ACTION-002</para>
            /// </summary>
            public const string ACTION_002 = "ACTION-002";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example We are going back up. Now.</para>
            /// <para>@actors kael</para>
            /// <para>@emotion angry x90</para>
            /// <para>@next out -&gt; DIALOG-002</para>
            /// <para>@note Kael reprend le contrôle et renvoie tout le monde au début du pont.</para>
            /// <para>@key __blueprints__.reactor_breach.DIALOG-009</para>
            /// </summary>
            public const string DIALOG_009 = "DIALOG-009";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example {:a2}That is enough for one shift. Seal {{#ui.hud.airlock_label}}.</para>
            /// <para>@actors nora</para>
            /// <para>@emotion joy x15</para>
            /// <para>@note Dernière réplique : aucun fil ne part d'ici.</para>
            /// <para>@key __blueprints__.reactor_breach.DIALOG-010</para>
            /// </summary>
            public const string DIALOG_010 = "DIALOG-010";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Do not touch the coupling, {{@a2}}. I mean it.</para>
            /// <para>@actors kael</para>
            /// <para>@emotion angry x80</para>
            /// <para>@next out -&gt; DIALOG-012</para>
            /// <para>@note Kael ment : il sait très bien ce qu'il y a derrière le couplage, il l'a vu au pont 3.</para>
            /// <para>@key __blueprints__.reactor_breach.DIALOG-011</para>
            /// </summary>
            public const string DIALOG_011 = "DIALOG-011";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Good morning. Today is the fourteenth of a month I no longer hold.</para>
            /// <para>@actors oracle</para>
            /// <para>@emotion neutral x5</para>
            /// <para>@next out -&gt; DIALOG-007</para>
            /// <para>@note L'Oracle parle par-dessus les autres, sans attendre son tour.</para>
            /// <para>@key __blueprints__.reactor_breach.DIALOG-012</para>
            /// </summary>
            public const string DIALOG_012 = "DIALOG-012";
        }
        /// <summary>
        /// <para>@scene docking_ring_brief</para>
        /// </summary>
        public static class docking_ring_brief
        {
            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@start</para>
            /// <para>@example {{#ui.hud.airlock_label}}.{|} Two minutes, {{@a1}}.</para>
            /// <para>@actors nora</para>
            /// <para>@emotion neutral x10</para>
            /// <para>@next out -&gt; CHOICE-001</para>
            /// <para>@note Scène courte : elle existe surtout pour vérifier qu'un export séparé produit bien deux fichiers.</para>
            /// <para>@key __blueprints__.docking_ring_brief.DIALOG-001</para>
            /// </summary>
            public const string DIALOG_001 = "DIALOG-001";

            /// <summary>
            /// <para>@type choice</para>
            /// <para>@actors nora</para>
            /// <para>@options C1, C2, C3</para>
            /// <para>@next C1 -&gt; ACTION-001, C2 -&gt; DIALOG-002, C3 -&gt; DIALOG-001</para>
            /// <para>@note Deux de ces réponses lisent leur texte dans une clé d'interface partagée, la troisième a la sienne.</para>
            /// <para>@key __blueprints__.docking_ring_brief.CHOICE-001</para>
            /// </summary>
            public const string CHOICE_001 = "CHOICE-001";

            /// <summary>
            /// <para>@type action</para>
            /// <para>@calls set_switch, play_music</para>
            /// <para>@next then -&gt; DIALOG-002, catch -&gt; DIALOG-002</para>
            /// <para>@note Kael a déjà lancé la séquence avant qu'elle réponde.</para>
            /// <para>@key __blueprints__.docking_ring_brief.ACTION-001</para>
            /// </summary>
            public const string ACTION_001 = "ACTION-001";

            /// <summary>
            /// <para>@type dialog</para>
            /// <para>@example Told you it would hold.</para>
            /// <para>@actors kael</para>
            /// <para>@emotion joy x55</para>
            /// <para>@note Kael se donne raison alors qu'il n'en savait rien.</para>
            /// <para>@key __blueprints__.docking_ring_brief.DIALOG-002</para>
            /// </summary>
            public const string DIALOG_002 = "DIALOG-002";
        }
    }
    /// <summary>
    /// <para>Every option id, grouped by scene then by choice block. An option id is also its exit port.</para>
    /// </summary>
    public static class Options
    {
        /// <summary>
        /// <para>@scene reactor_breach</para>
        /// </summary>
        public static class reactor_breach
        {
            /// <summary>
            /// <para>@block CHOICE-001</para>
            /// </summary>
            public static class CHOICE_001
            {
                /// <summary>
                /// <para>@example What did you see on deck three, {{@a1}}?</para>
                /// <para>@key __blueprints__.reactor_breach.CHOICE-001.C1</para>
                /// </summary>
                public const string C1 = "C1";

                /// <summary>
                /// <para>@example I am not going any further.</para>
                /// <para>@key __blueprints__.reactor_breach.CHOICE-001.C2</para>
                /// </summary>
                public const string C2 = "C2";

                /// <summary>
                /// <para>@example Name your price.</para>
                /// <para>@conditional</para>
                /// <para>@key __blueprints__.reactor_breach.CHOICE-001.C3</para>
                /// </summary>
                public const string C3 = "C3";

                /// <summary>
                /// <para>@example (Say nothing and watch him.)</para>
                /// <para>@conditional</para>
                /// <para>@key __blueprints__.reactor_breach.CHOICE-001.C4</para>
                /// </summary>
                public const string C4 = "C4";
            }
        }
        /// <summary>
        /// <para>@scene docking_ring_brief</para>
        /// </summary>
        public static class docking_ring_brief
        {
            /// <summary>
            /// <para>@block CHOICE-001</para>
            /// </summary>
            public static class CHOICE_001
            {
                /// <summary>
                /// <para>@example Yes</para>
                /// <para>@key ui.common.yes</para>
                /// </summary>
                public const string C1 = "C1";

                /// <summary>
                /// <para>@example No</para>
                /// <para>@key ui.common.no</para>
                /// </summary>
                public const string C2 = "C2";

                /// <summary>
                /// <para>@example Give me one more minute.</para>
                /// <para>@conditional</para>
                /// <para>@key __blueprints__.docking_ring_brief.CHOICE-001.C3</para>
                /// </summary>
                public const string C3 = "C3";
            }
        }
    }
    /// <summary>
    /// <para>Every card the blocks may cite, under its game name. The value is the id that actors carries.</para>
    /// </summary>
    public static class Cards
    {
        /// <summary>
        /// <para>@name kael</para>
        /// <para>@role characters</para>
        /// </summary>
        public const string kael = "var1";

        /// <summary>
        /// <para>@name nora</para>
        /// <para>@role characters</para>
        /// </summary>
        public const string nora = "var2";

        /// <summary>
        /// <para>@name oracle</para>
        /// <para>@role characters</para>
        /// </summary>
        public const string oracle = "var3";

        /// <summary>
        /// <para>@name vesk</para>
        /// <para>@role characters</para>
        /// </summary>
        public const string vesk = "var4";

        /// <summary>
        /// <para>@name neutral</para>
        /// <para>@role emotions</para>
        /// </summary>
        public const string neutral = "var5";

        /// <summary>
        /// <para>@name angry</para>
        /// <para>@role emotions</para>
        /// </summary>
        public const string angry = "var6";

        /// <summary>
        /// <para>@name afraid</para>
        /// <para>@role emotions</para>
        /// </summary>
        public const string afraid = "var7";

        /// <summary>
        /// <para>@name joy</para>
        /// <para>@role emotions</para>
        /// </summary>
        public const string joy = "var8";

        /// <summary>
        /// <para>@name suspicious</para>
        /// <para>@role emotions</para>
        /// </summary>
        public const string suspicious = "var9";

        /// <summary>
        /// <para>@name reactor_deck</para>
        /// <para>@role places</para>
        /// </summary>
        public const string reactor_deck = "var10";

        /// <summary>
        /// <para>@name docking_ring</para>
        /// <para>@role places</para>
        /// </summary>
        public const string docking_ring = "var11";

        /// <summary>
        /// <para>@name plasma_cell</para>
        /// <para>@role none</para>
        /// </summary>
        public const string plasma_cell = "var12";

        /// <summary>
        /// <para>@name keycard</para>
        /// <para>@role none</para>
        /// </summary>
        public const string keycard = "var13";

        /// <summary>
        /// <para>@name ration</para>
        /// <para>@role none</para>
        /// </summary>
        public const string ration = "var14";
    }
    /// <summary>
    /// <para>Every dictionary id, as ConditionTest.dict cites it.</para>
    /// </summary>
    public static class Dictionaries
    {
        /// <summary>
        /// <para>@type boolean</para>
        /// <para>@entries 5</para>
        /// </summary>
        public const string switches = "switches";

        /// <summary>
        /// <para>@type number</para>
        /// <para>@entries 4</para>
        /// </summary>
        public const string variables = "variables";

        /// <summary>
        /// <para>@type number</para>
        /// <para>@entries 3</para>
        /// </summary>
        public const string items = "items";

        /// <summary>
        /// <para>@type string</para>
        /// <para>@entries 3</para>
        /// </summary>
        public const string flags = "flags";
    }
    /// <summary>
    /// <para>Every entry key, grouped by dictionary: what ConditionTest.entry cites.</para>
    /// </summary>
    public static class DictionaryEntries
    {
        /// <summary>
        /// <para>@dictionary switches</para>
        /// <para>@type boolean</para>
        /// </summary>
        public static class switches
        {
            public const string door_unlocked = "door_unlocked";
            public const string oracle_awake = "oracle_awake";
            public const string reactor_stable = "reactor_stable";
            public const string met_vesk = "met_vesk";
            public const string alarm_armed = "alarm_armed";
        }
        /// <summary>
        /// <para>@dictionary variables</para>
        /// <para>@type number</para>
        /// </summary>
        public static class variables
        {
            public const string chapter = "chapter";
            public const string credits = "credits";
            public const string trust_kael = "trust_kael";
            public const string alarm_level = "alarm_level";
        }
        /// <summary>
        /// <para>@dictionary items</para>
        /// <para>@type number</para>
        /// </summary>
        public static class items
        {
            public const string plasma_cell = "plasma_cell";
            public const string keycard = "keycard";
            public const string ration = "ration";
        }
        /// <summary>
        /// <para>@dictionary flags</para>
        /// <para>@type string</para>
        /// </summary>
        public static class flags
        {
            public const string faction = "faction";
            public const string last_port = "last_port";
            public const string player_callsign = "player_callsign";
        }
    }
    /// <summary>
    /// <para>Every engine function id, as ActionCall.fn names it.</para>
    /// </summary>
    public static class Functions
    {
        /// <summary>
        /// <para>@params track: string, fadeMs: number, loop: boolean</para>
        /// </summary>
        public const string play_music = "play_music";

        /// <summary>
        /// <para>@params flag: dictionaryKey(switches), value: boolean</para>
        /// </summary>
        public const string set_switch = "set_switch";

        /// <summary>
        /// <para>@params item: dictionaryKey(items), count: number</para>
        /// </summary>
        public const string add_item = "add_item";

        /// <summary>
        /// <para>@params counter: dictionaryKey(variables), value: number</para>
        /// </summary>
        public const string set_counter = "set_counter";

        /// <summary>
        /// <para>@params flag: dictionaryKey(flags), value: string</para>
        /// </summary>
        public const string write_flag = "write_flag";

        /// <summary>
        /// <para>@params intensity: number, durationMs: number</para>
        /// </summary>
        public const string shake_camera = "shake_camera";

        /// <summary>
        /// <para>@params id: string</para>
        /// </summary>
        public const string unlock_achievement = "unlock_achievement";

        /// <summary>
        /// <para>@params (none)</para>
        /// </summary>
        public const string close_bulkhead = "close_bulkhead";
    }
    /// <summary>
    /// <para>Every parameter name, grouped by function: the keys of ActionCall.args.</para>
    /// </summary>
    public static class FunctionParams
    {
        /// <summary>
        /// <para>@function play_music</para>
        /// </summary>
        public static class play_music
        {
            /// <summary>
            /// <para>@type string</para>
            /// </summary>
            public const string track = "track";

            /// <summary>
            /// <para>@type number</para>
            /// </summary>
            public const string fadeMs = "fadeMs";

            /// <summary>
            /// <para>@type boolean</para>
            /// </summary>
            public const string loop = "loop";
        }
        /// <summary>
        /// <para>@function set_switch</para>
        /// </summary>
        public static class set_switch
        {
            /// <summary>
            /// <para>@type dictionaryKey (switches)</para>
            /// </summary>
            public const string flag = "flag";

            /// <summary>
            /// <para>@type boolean</para>
            /// </summary>
            public const string value = "value";
        }
        /// <summary>
        /// <para>@function add_item</para>
        /// </summary>
        public static class add_item
        {
            /// <summary>
            /// <para>@type dictionaryKey (items)</para>
            /// </summary>
            public const string item = "item";

            /// <summary>
            /// <para>@type number</para>
            /// </summary>
            public const string count = "count";
        }
        /// <summary>
        /// <para>@function set_counter</para>
        /// </summary>
        public static class set_counter
        {
            /// <summary>
            /// <para>@type dictionaryKey (variables)</para>
            /// </summary>
            public const string counter = "counter";

            /// <summary>
            /// <para>@type number</para>
            /// </summary>
            public const string value = "value";
        }
        /// <summary>
        /// <para>@function write_flag</para>
        /// </summary>
        public static class write_flag
        {
            /// <summary>
            /// <para>@type dictionaryKey (flags)</para>
            /// </summary>
            public const string flag = "flag";

            /// <summary>
            /// <para>@type string</para>
            /// </summary>
            public const string value = "value";
        }
        /// <summary>
        /// <para>@function shake_camera</para>
        /// </summary>
        public static class shake_camera
        {
            /// <summary>
            /// <para>@type number</para>
            /// </summary>
            public const string intensity = "intensity";

            /// <summary>
            /// <para>@type number</para>
            /// </summary>
            public const string durationMs = "durationMs";
        }
        /// <summary>
        /// <para>@function unlock_achievement</para>
        /// </summary>
        public static class unlock_achievement
        {
            /// <summary>
            /// <para>@type string</para>
            /// </summary>
            public const string id = "id";
        }
        /// <summary>
        /// <para>@function close_bulkhead</para>
        /// </summary>
        public static class close_bulkhead
        {
        }
    }
}
