#pragma once
// Auto-generated by LSDE. Do not edit manually.
// The shape of Engine-Conformance-Scene.blueprints.json (format "lsde-blueprints", version 1).
// Field names follow the exporter's naming convention (asIs): they match the file exactly.
// The standard library has no JSON reader: fill these structs with the one your engine ships
// (nlohmann/json, RapidJSON, Unreal's FJsonObject).

#include <map>
#include <optional>
#include <string>
#include <variant>
#include <vector>

namespace EngineConformanceSceneBlueprints {

/** What a block is. Decides which optional fields it carries. */
namespace BlockType {
inline constexpr const char* Dialog = "dialog";
inline constexpr const char* Choice = "choice";
inline constexpr const char* Condition = "condition";
inline constexpr const char* Action = "action";
inline constexpr const char* Note = "note";
}  // namespace BlockType

/** How a condition compares a dictionary entry to its value. */
namespace ConditionOperator {
inline constexpr const char* Equals = "equals";
inline constexpr const char* NotEquals = "notEquals";
inline constexpr const char* LessThan = "lessThan";
inline constexpr const char* LessOrEqual = "lessOrEqual";
inline constexpr const char* GreaterThan = "greaterThan";
inline constexpr const char* GreaterOrEqual = "greaterOrEqual";
}  // namespace ConditionOperator

/** How a comparison links to the one above it. The list is flat: precedence is yours. */
namespace ConditionJoin {
inline constexpr const char* And = "and";
inline constexpr const char* Or = "or";
}  // namespace ConditionJoin

/** What a function parameter accepts: a literal, or a key picked in a dictionary. */
namespace ValueType {
inline constexpr const char* Boolean = "boolean";
inline constexpr const char* String = "string";
inline constexpr const char* Number = "number";
inline constexpr const char* DictionaryKey = "dictionaryKey";
}  // namespace ValueType

/** What a dictionary stores, hence what its entries are compared to. */
namespace LiteralValueType {
inline constexpr const char* Boolean = "boolean";
inline constexpr const char* String = "string";
inline constexpr const char* Number = "number";
}  // namespace LiteralValueType

/** What a card is used for in the editor. */
namespace CardRole {
inline constexpr const char* None = "none";
inline constexpr const char* Characters = "characters";
inline constexpr const char* Emotions = "emotions";
inline constexpr const char* Places = "places";
}  // namespace CardRole

/** The ports every engine must know. Option, case and actor ports are named by the project. */
namespace Ports {
/** The single entry port of every block. */
inline constexpr const char* In = "in";
/** The default exit of a dialog, and the true exit of an if-style condition. */
inline constexpr const char* Out = "out";
/** The exit of an action block once its calls succeeded. */
inline constexpr const char* Then = "then";
/** The exit of an action block when a call failed. */
inline constexpr const char* Catch = "catch";
/** The fallback exit of a condition block: no case matched. */
inline constexpr const char* Default = "default";
/** NOT a port: the reserved ConditionTest.dict that reads past answers. entry is a CHOICE block id, value an Option.id of that block. The engine answers it from what it recorded during the scene; the memory starts and ends with the scene, and no project dictionary may use this id. */
inline constexpr const char* Choice = "choice";
}  // namespace Ports

/** A text by locale code. */
using TextByLocale = std::map<std::string, std::string>;
/** What a property, an argument or a condition value can hold. */
using PropertyValue = std::variant<bool, double, std::string>;
/** Named property values, keyed by the ids the project declared. */
using PropertyBag = std::map<std::string, PropertyValue>;

/** Which software wrote the file, to trace a delivered payload back to its version. */
struct Generator {
	/** Always LSDE. */
	std::string app;

	/** The software version, e.g. 2.0.3 - not the format version. */
	std::string version;
};

/** A dictionary the engine maintains, as declared in the project. Conditions cite it by id. */
struct DictionaryDefinition {
	/** The dictionary id, as ConditionTest.dict cites it. */
	std::string id;

	/** What its entries are compared to. */
	std::string valueType;

	/** The entry keys, in declaration order. */
	std::vector<std::string> entries;
};

/** One parameter of an engine function. */
struct FunctionParameter {
	/** The argument name, as ActionCall.args keys it. */
	std::string name;

	/** What the argument holds. */
	std::string type;

	/** Only when type is dictionaryKey: where the value is picked. Absent = empty or std::nullopt. */
	std::optional<std::string> dictionary;
};

/** A function the engine implements, as ActionCall.fn names it. */
struct FunctionDefinition {
	/** The function id. */
	std::string id;

	/** Its parameters, in declaration order. */
	std::vector<FunctionParameter> params;
};

/** A card cited by blocks: the other end of Block.actors and Block.emotion. */
struct Card {
	/** The stable editor id (var3) that blocks reference. */
	std::string id;

	/** The name the game gives this card, never the editor label. */
	std::string name;

	/** What the card is used for. */
	std::string role;
};

/** An outgoing wire, seen from the block that carries it. */
struct Link {
	/** The exit port: a fixed port (see Ports), an option id, a case port or an actor id. */
	std::string port;

	/** The target block id, relative to the same scene. */
	std::string to;

	/** The target's entry port, always in today. */
	std::string toPort;
};

/** What an action block asks the engine to run. */
struct ActionCall {
	/** The function id. May be empty when the designer has not picked one yet. */
	std::string fn;

	/** The arguments BY NAME, as declared in FunctionDefinition.params. */
	PropertyBag args;
};

/** One comparison: a dictionary entry against a value. The reserved dict id "choice" is the exception — it reads the answers the player already gave IN THIS SCENE, which the engine tracks on its own. No project dictionary can be named that. */
struct ConditionTest {
	/** The dictionary id, see DictionaryDefinition.id. "choice" is reserved: see Ports.Choice. */
	std::string dict;

	/** The entry read in that dictionary. With dict "choice", a CHOICE block id of this scene. */
	std::string entry;

	/** The comparison. */
	std::string op;

	/** The right-hand side; its type follows the dictionary's valueType. With dict "choice", the Option.id the player picked. */
	PropertyValue value;

	/** Link with the comparison ABOVE. Absent on the first one. Absent = empty or std::nullopt. */
	std::optional<std::string> join;
};

/** One case of a condition block: the exit port, and what must hold for it. */
struct ConditionCase {
	/** The exit port of this case (K1...), or the block's out when cases share one exit. */
	std::string port;

	/** Absent = always true. Such a case makes every following case unreachable. Absent = empty or std::nullopt. */
	std::vector<ConditionTest> when;
};

/** One answer of a choice block, a translated key in its own right. */
struct Option {
	/** The option id, which is also its exit port (C1...). */
	std::string id;

	/** The full i18n key of its text. */
	std::string key;

	/** Its text by locale, when texts are exported. Absent = empty or std::nullopt. */
	TextByLocale text;

	/** Absent = always offered. Absent = empty or std::nullopt. */
	std::vector<ConditionTest> when;
};

/** A node of the graph. type decides which optional fields are present. */
struct Block {
	/** Identity RELATIVE to its scene (DIALOG-002): what links and Scene.start reference. */
	std::string id;

	/** The full i18n key, as localization files carry it. */
	std::string key;

	/** The readable name (its summary), when written. Absent = empty or std::nullopt. */
	std::optional<std::string> label;

	/** Readable names above the block, root first. Empty ones are skipped. Absent = empty or std::nullopt. */
	std::vector<std::string> parentLabels;

	/** What the block is. */
	std::string type;

	/** Card ids of who speaks. Resolve them through Blueprints.cards. Absent = empty or std::nullopt. */
	std::vector<std::string> actors;

	/** Card id of the emotion, when one is set. Absent = empty or std::nullopt. */
	std::optional<std::string> emotion;

	/** Only with emotion. Absent = empty or std::nullopt. */
	std::optional<double> intensity;

	/** The line by locale, dialogs only, when texts are exported. Absent = empty or std::nullopt. */
	TextByLocale text;

	/** The body of a note block: never translated, only when notes are exported. Absent = empty or std::nullopt. */
	std::optional<std::string> body;

	/** The team note on the block, only when notes are exported. Absent = empty or std::nullopt. */
	std::optional<std::string> note;

	/** Properties SET on the block, native and project-declared alike, by id. Ids never collide: a project property cannot take a native name. One native holds a LIST rather than a scalar: waitForBlocks, an array of block ids OF THIS SCENE the block waits for before it advances - the counterpart of isAsync. Absent = empty or std::nullopt. */
	PropertyBag props;

	/** Action blocks: what to run, in order. Absent = empty or std::nullopt. */
	std::vector<ActionCall> calls;

	/** Condition blocks: the cases, in evaluation order. Absent = empty or std::nullopt. */
	std::vector<ConditionCase> cases;

	/** Choice blocks: the answers, in display order. Absent = empty or std::nullopt. */
	std::vector<Option> options;

	/** Outgoing wires. Absent when nothing leaves the block. Absent = empty or std::nullopt. */
	std::vector<Link> next;
};

/** One scene: its blocks, and where it starts. */
struct Scene {
	/** The scene path without the reserved namespace (acte1, chap1.acte1). */
	std::string scene;

	/** The readable name of the scene, when written. Absent = empty or std::nullopt. */
	std::optional<std::string> label;

	/** The entry block id. Absent = the scene has no entry and cannot play. Absent = empty or std::nullopt. */
	std::optional<std::string> start;

	/** Every exported block of the scene. */
	std::vector<Block> blocks;
};

/** The whole file. One scene per file or all of them: the only difference between the two split modes. */
struct Blueprints {
	/** Always lsde-blueprints. */
	std::string format;

	/** The FORMAT version. Bumps only when this contract changes. */
	int version;

	/** Which software wrote the file. */
	Generator generator;

	/** ISO 8601 instant of the export. */
	std::string exportedAt;

	/** The project name. */
	std::string project;

	/** Every locale of the project. */
	std::vector<std::string> locales;

	/** The locale that is written first. Empty when the project declares none. */
	std::string referenceLocale;

	/** The declared vocabulary, whole, never trimmed to the exported scenes. */
	std::vector<DictionaryDefinition> dictionaries;

	/** The declared engine functions. */
	std::vector<FunctionDefinition> functions;

	/** The cards that blocks may cite. */
	std::vector<Card> cards;

	/** The scenes carried by this file. */
	std::vector<Scene> scenes;
};

/** The whole file, under the project's name. Same as Blueprints. */
using EngineConformanceSceneBlueprintsFile = Blueprints;

}  // namespace EngineConformanceSceneBlueprints
