# Auto-generated by LSDE. Do not edit manually.
# The shape of Engine-Conformance-Scene.blueprints.json (format "lsde-blueprints", version 1).
# Field names follow the exporter's naming convention (asIs): they match the file exactly.
class_name EngineConformanceSceneBlueprints
extends RefCounted
## The types of the payload. The whole file is [EngineConformanceSceneBlueprints.Blueprints]:
## load it with [method EngineConformanceSceneBlueprints.from_file] or [method EngineConformanceSceneBlueprints.from_json_text].

const FORMAT = "lsde-blueprints"
const VERSION = 1

## What a block is. Decides which optional fields it carries.
class BlockType:
	const DIALOG = "dialog"
	const CHOICE = "choice"
	const CONDITION = "condition"
	const ACTION = "action"
	const NOTE = "note"

## How a condition compares a dictionary entry to its value.
class ConditionOperator:
	const EQUALS = "equals"
	const NOT_EQUALS = "notEquals"
	const LESS_THAN = "lessThan"
	const LESS_OR_EQUAL = "lessOrEqual"
	const GREATER_THAN = "greaterThan"
	const GREATER_OR_EQUAL = "greaterOrEqual"

## How a comparison links to the one above it. The list is flat: precedence is yours.
class ConditionJoin:
	const AND = "and"
	const OR = "or"

## What a function parameter accepts: a literal, or a key picked in a dictionary.
class ValueType:
	const BOOLEAN = "boolean"
	const STRING = "string"
	const NUMBER = "number"
	const DICTIONARY_KEY = "dictionaryKey"

## What a dictionary stores, hence what its entries are compared to.
class LiteralValueType:
	const BOOLEAN = "boolean"
	const STRING = "string"
	const NUMBER = "number"

## What a card is used for in the editor.
class CardRole:
	const NONE = "none"
	const CHARACTERS = "characters"
	const EMOTIONS = "emotions"
	const PLACES = "places"

## The ports every engine must know. Option, case and actor ports are named by the project.
class Ports:
	## The single entry port of every block.
	const IN = "in"
	## The default exit of a dialog, and the true exit of an if-style condition.
	const OUT = "out"
	## The exit of an action block once its calls succeeded.
	const THEN = "then"
	## The exit of an action block when a call failed.
	const CATCH = "catch"
	## The fallback exit of a condition block: no case matched.
	const DEFAULT = "default"
	## NOT a port: the reserved ConditionTest.dict that reads past answers. entry is a CHOICE block id, value an Option.id of that block. The engine answers it from what it recorded during the scene; the memory starts and ends with the scene, and no project dictionary may use this id.
	const CHOICE = "choice"

## Which software wrote the file, to trace a delivered payload back to its version.
class Generator:
	## Always LSDE.
	var app: String = ""

	## The software version, e.g. 2.0.3 - not the format version.
	var version: String = ""

	static func from_dict(d: Dictionary) -> Generator:
		var r := Generator.new()
		r.app = str(d.get("app", ""))
		r.version = str(d.get("version", ""))
		return r

## A dictionary the engine maintains, as declared in the project. Conditions cite it by id.
class DictionaryDefinition:
	## The dictionary id, as ConditionTest.dict cites it.
	var id: String = ""

	## What its entries are compared to.
	var valueType: String = ""

	## The entry keys, in declaration order.
	var entries: Array[String] = []

	static func from_dict(d: Dictionary) -> DictionaryDefinition:
		var r := DictionaryDefinition.new()
		r.id = str(d.get("id", ""))
		r.valueType = str(d.get("valueType", ""))
		for item in d.get("entries", []):
			r.entries.append(str(item))
		return r

## One parameter of an engine function.
class FunctionParameter:
	## The argument name, as ActionCall.args keys it.
	var name: String = ""

	## What the argument holds.
	var type: String = ""

	## Only when type is dictionaryKey: where the value is picked. Absent = default.
	var dictionary: String = ""

	static func from_dict(d: Dictionary) -> FunctionParameter:
		var r := FunctionParameter.new()
		r.name = str(d.get("name", ""))
		r.type = str(d.get("type", ""))
		r.dictionary = str(d.get("dictionary", ""))
		return r

## A function the engine implements, as ActionCall.fn names it.
class FunctionDefinition:
	## The function id.
	var id: String = ""

	## Its parameters, in declaration order.
	var params: Array[FunctionParameter] = []

	static func from_dict(d: Dictionary) -> FunctionDefinition:
		var r := FunctionDefinition.new()
		r.id = str(d.get("id", ""))
		for item in d.get("params", []):
			r.params.append(FunctionParameter.from_dict(item))
		return r

## A card cited by blocks: the other end of Block.actors and Block.emotion.
class Card:
	## The stable editor id (var3) that blocks reference.
	var id: String = ""

	## The name the game gives this card, never the editor label.
	var name: String = ""

	## What the card is used for.
	var role: String = ""

	static func from_dict(d: Dictionary) -> Card:
		var r := Card.new()
		r.id = str(d.get("id", ""))
		r.name = str(d.get("name", ""))
		r.role = str(d.get("role", ""))
		return r

## An outgoing wire, seen from the block that carries it.
class Link:
	## The exit port: a fixed port (see Ports), an option id, a case port or an actor id.
	var port: String = ""

	## The target block id, relative to the same scene.
	var to: String = ""

	## The target's entry port, always in today.
	var toPort: String = ""

	static func from_dict(d: Dictionary) -> Link:
		var r := Link.new()
		r.port = str(d.get("port", ""))
		r.to = str(d.get("to", ""))
		r.toPort = str(d.get("toPort", ""))
		return r

## What an action block asks the engine to run.
class ActionCall:
	## The function id. May be empty when the designer has not picked one yet.
	var fn: String = ""

	## The arguments BY NAME, as declared in FunctionDefinition.params.
	var args: Dictionary = {}

	static func from_dict(d: Dictionary) -> ActionCall:
		var r := ActionCall.new()
		r.fn = str(d.get("fn", ""))
		r.args = d.get("args", {})
		return r

## One comparison: a dictionary entry against a value. The reserved dict id "choice" is the exception — it reads the answers the player already gave IN THIS SCENE, which the engine tracks on its own. No project dictionary can be named that.
class ConditionTest:
	## The dictionary id, see DictionaryDefinition.id. "choice" is reserved: see Ports.Choice.
	var dict: String = ""

	## The entry read in that dictionary. With dict "choice", a CHOICE block id of this scene.
	var entry: String = ""

	## The comparison.
	var op: String = ""

	## The right-hand side; its type follows the dictionary's valueType. With dict "choice", the Option.id the player picked.
	var value: Variant = null

	## Link with the comparison ABOVE. Absent on the first one. Absent = default.
	var join: String = ""

	static func from_dict(d: Dictionary) -> ConditionTest:
		var r := ConditionTest.new()
		r.dict = str(d.get("dict", ""))
		r.entry = str(d.get("entry", ""))
		r.op = str(d.get("op", ""))
		r.value = d.get("value")
		r.join = str(d.get("join", ""))
		return r

## One case of a condition block: the exit port, and what must hold for it.
class ConditionCase:
	## The exit port of this case (K1...), or the block's out when cases share one exit.
	var port: String = ""

	## Absent = always true. Such a case makes every following case unreachable. Absent = default.
	var when_: Array[ConditionTest] = []

	static func from_dict(d: Dictionary) -> ConditionCase:
		var r := ConditionCase.new()
		r.port = str(d.get("port", ""))
		for item in d.get("when", []):
			r.when_.append(ConditionTest.from_dict(item))
		return r

## One answer of a choice block, a translated key in its own right.
class Option:
	## The option id, which is also its exit port (C1...).
	var id: String = ""

	## The full i18n key of its text.
	var key: String = ""

	## Its text by locale, when texts are exported. Absent = default.
	var text: Dictionary = {}

	## Absent = always offered. Absent = default.
	var when_: Array[ConditionTest] = []

	static func from_dict(d: Dictionary) -> Option:
		var r := Option.new()
		r.id = str(d.get("id", ""))
		r.key = str(d.get("key", ""))
		r.text = d.get("text", {})
		for item in d.get("when", []):
			r.when_.append(ConditionTest.from_dict(item))
		return r

## A node of the graph. type decides which optional fields are present.
class Block:
	## Identity RELATIVE to its scene (DIALOG-002): what links and Scene.start reference.
	var id: String = ""

	## The full i18n key, as localization files carry it.
	var key: String = ""

	## The readable name (its summary), when written. Absent = default.
	var label: String = ""

	## Readable names above the block, root first. Empty ones are skipped. Absent = default.
	var parentLabels: Array[String] = []

	## What the block is.
	var type: String = ""

	## Card ids of who speaks. Resolve them through Blueprints.cards. Absent = default.
	var actors: Array[String] = []

	## Card id of the emotion, when one is set. Absent = default.
	var emotion: String = ""

	## Only with emotion. Absent = default.
	var intensity: float = 0.0

	## The line by locale, dialogs only, when texts are exported. Absent = default.
	var text: Dictionary = {}

	## The body of a note block: never translated, only when notes are exported. Absent = default.
	var body: String = ""

	## The team note on the block, only when notes are exported. Absent = default.
	var note: String = ""

	## Properties SET on the block, native and project-declared alike, by id. Ids never collide: a project property cannot take a native name. One native holds a LIST rather than a scalar: waitForBlocks, an array of block ids OF THIS SCENE the block waits for before it advances - the counterpart of isAsync. Absent = default.
	var props: Dictionary = {}

	## Action blocks: what to run, in order. Absent = default.
	var calls: Array[ActionCall] = []

	## Condition blocks: the cases, in evaluation order. Absent = default.
	var cases: Array[ConditionCase] = []

	## Choice blocks: the answers, in display order. Absent = default.
	var options: Array[Option] = []

	## Outgoing wires. Absent when nothing leaves the block. Absent = default.
	var next: Array[Link] = []

	static func from_dict(d: Dictionary) -> Block:
		var r := Block.new()
		r.id = str(d.get("id", ""))
		r.key = str(d.get("key", ""))
		r.label = str(d.get("label", ""))
		for item in d.get("parentLabels", []):
			r.parentLabels.append(str(item))
		r.type = str(d.get("type", ""))
		for item in d.get("actors", []):
			r.actors.append(str(item))
		r.emotion = str(d.get("emotion", ""))
		r.intensity = float(d.get("intensity", 0.0))
		r.text = d.get("text", {})
		r.body = str(d.get("body", ""))
		r.note = str(d.get("note", ""))
		r.props = d.get("props", {})
		for item in d.get("calls", []):
			r.calls.append(ActionCall.from_dict(item))
		for item in d.get("cases", []):
			r.cases.append(ConditionCase.from_dict(item))
		for item in d.get("options", []):
			r.options.append(Option.from_dict(item))
		for item in d.get("next", []):
			r.next.append(Link.from_dict(item))
		return r

## One scene: its blocks, and where it starts.
class Scene:
	## The scene path without the reserved namespace (acte1, chap1.acte1).
	var scene: String = ""

	## The readable name of the scene, when written. Absent = default.
	var label: String = ""

	## The entry block id. Absent = the scene has no entry and cannot play. Absent = default.
	var start: String = ""

	## Every exported block of the scene.
	var blocks: Array[Block] = []

	static func from_dict(d: Dictionary) -> Scene:
		var r := Scene.new()
		r.scene = str(d.get("scene", ""))
		r.label = str(d.get("label", ""))
		r.start = str(d.get("start", ""))
		for item in d.get("blocks", []):
			r.blocks.append(Block.from_dict(item))
		return r

## The whole file. One scene per file or all of them: the only difference between the two split modes.
class Blueprints:
	## Always lsde-blueprints.
	var format: String = ""

	## The FORMAT version. Bumps only when this contract changes.
	var version: int = 0

	## Which software wrote the file.
	var generator: Generator = null

	## ISO 8601 instant of the export.
	var exportedAt: String = ""

	## The project name.
	var project: String = ""

	## Every locale of the project.
	var locales: Array[String] = []

	## The locale that is written first. Empty when the project declares none.
	var referenceLocale: String = ""

	## The declared vocabulary, whole, never trimmed to the exported scenes.
	var dictionaries: Array[DictionaryDefinition] = []

	## The declared engine functions.
	var functions: Array[FunctionDefinition] = []

	## The cards that blocks may cite.
	var cards: Array[Card] = []

	## The scenes carried by this file.
	var scenes: Array[Scene] = []

	static func from_dict(d: Dictionary) -> Blueprints:
		var r := Blueprints.new()
		r.format = str(d.get("format", ""))
		r.version = int(d.get("version", 0))
		if d.has("generator"):
			r.generator = Generator.from_dict(d["generator"])
		r.exportedAt = str(d.get("exportedAt", ""))
		r.project = str(d.get("project", ""))
		for item in d.get("locales", []):
			r.locales.append(str(item))
		r.referenceLocale = str(d.get("referenceLocale", ""))
		for item in d.get("dictionaries", []):
			r.dictionaries.append(DictionaryDefinition.from_dict(item))
		for item in d.get("functions", []):
			r.functions.append(FunctionDefinition.from_dict(item))
		for item in d.get("cards", []):
			r.cards.append(Card.from_dict(item))
		for item in d.get("scenes", []):
			r.scenes.append(Scene.from_dict(item))
		return r

## Parses the text of the payload file. Returns null and pushes an error when it is not a JSON object.
static func from_json_text(text: String) -> Blueprints:
	var parsed = JSON.parse_string(text)
	if not (parsed is Dictionary):
		push_error("EngineConformanceSceneBlueprints: the payload is not a JSON object")
		return null
	return Blueprints.from_dict(parsed)

## Reads and parses the payload file at [param path] (res://, user:// or absolute).
static func from_file(path: String) -> Blueprints:
	return from_json_text(FileAccess.get_file_as_string(path))
