// Auto-generated by LSDE. Do not edit manually.
// The shape of Engine-Conformance-Scene.blueprints.json (format "lsde-blueprints", version 1).
// Field names follow the exporter's naming convention (asIs): they match the file exactly.

/** What a block is. Decides which optional fields it carries. */
export const BlockType = {
	Dialog: "dialog",
	Choice: "choice",
	Condition: "condition",
	Action: "action",
	Note: "note",
} as const;
export type BlockType = (typeof BlockType)[keyof typeof BlockType];

/** How a condition compares a dictionary entry to its value. */
export const ConditionOperator = {
	Equals: "equals",
	NotEquals: "notEquals",
	LessThan: "lessThan",
	LessOrEqual: "lessOrEqual",
	GreaterThan: "greaterThan",
	GreaterOrEqual: "greaterOrEqual",
} as const;
export type ConditionOperator = (typeof ConditionOperator)[keyof typeof ConditionOperator];

/** How a comparison links to the one above it. The list is flat: precedence is yours. */
export const ConditionJoin = {
	And: "and",
	Or: "or",
} as const;
export type ConditionJoin = (typeof ConditionJoin)[keyof typeof ConditionJoin];

/** What a function parameter accepts: a literal, or a key picked in a dictionary. */
export const ValueType = {
	Boolean: "boolean",
	String: "string",
	Number: "number",
	DictionaryKey: "dictionaryKey",
} as const;
export type ValueType = (typeof ValueType)[keyof typeof ValueType];

/** What a dictionary stores, hence what its entries are compared to. */
export const LiteralValueType = {
	Boolean: "boolean",
	String: "string",
	Number: "number",
} as const;
export type LiteralValueType = (typeof LiteralValueType)[keyof typeof LiteralValueType];

/** What a card is used for in the editor. */
export const CardRole = {
	None: "none",
	Characters: "characters",
	Emotions: "emotions",
	Places: "places",
} as const;
export type CardRole = (typeof CardRole)[keyof typeof CardRole];

/** The ports every engine must know. Option, case and actor ports are named by the project. */
export const Ports = {
	/** The single entry port of every block. */
	In: "in",
	/** The default exit of a dialog, and the true exit of an if-style condition. */
	Out: "out",
	/** The exit of an action block once its calls succeeded. */
	Then: "then",
	/** The exit of an action block when a call failed. */
	Catch: "catch",
	/** The fallback exit of a condition block: no case matched. */
	Default: "default",
	/** NOT a port: the reserved ConditionTest.dict that reads past answers. entry is a CHOICE block id, value an Option.id of that block. The engine answers it from what it recorded during the scene; the memory starts and ends with the scene, and no project dictionary may use this id. */
	Choice: "choice",
} as const;

/** A text by locale code, e.g. `{ en: "Hello", fr: "Bonjour" }`. */
export type TextByLocale = Record<string, string>;
/** What a property, an argument or a condition value can hold. */
export type PropertyValue = boolean | number | string;
/** Named property values, keyed by the ids the project declared. */
export type PropertyBag = Record<string, PropertyValue>;

/** Which software wrote the file, to trace a delivered payload back to its version. */
export interface Generator {
	/** Always LSDE. */
	app: "LSDE";
	/** The software version, e.g. 2.0.3 - not the format version. */
	version: string;
}

/** A dictionary the engine maintains, as declared in the project. Conditions cite it by id. */
export interface DictionaryDefinition {
	/** The dictionary id, as ConditionTest.dict cites it. */
	id: string;
	/** What its entries are compared to. */
	valueType: LiteralValueType;
	/** The entry keys, in declaration order. */
	entries: string[];
}

/** One parameter of an engine function. */
export interface FunctionParameter {
	/** The argument name, as ActionCall.args keys it. */
	name: string;
	/** What the argument holds. */
	type: ValueType;
	/** Only when type is dictionaryKey: where the value is picked. */
	dictionary?: string;
}

/** A function the engine implements, as ActionCall.fn names it. */
export interface FunctionDefinition {
	/** The function id. */
	id: string;
	/** Its parameters, in declaration order. */
	params: FunctionParameter[];
}

/** A card cited by blocks: the other end of Block.actors and Block.emotion. */
export interface Card {
	/** The stable editor id (var3) that blocks reference. */
	id: string;
	/** The name the game gives this card, never the editor label. */
	name: string;
	/** What the card is used for. */
	role: CardRole;
}

/** An outgoing wire, seen from the block that carries it. */
export interface Link {
	/** The exit port: a fixed port (see Ports), an option id, a case port or an actor id. */
	port: string;
	/** The target block id, relative to the same scene. */
	to: string;
	/** The target's entry port, always in today. */
	toPort: string;
}

/** What an action block asks the engine to run. */
export interface ActionCall {
	/** The function id. May be empty when the designer has not picked one yet. */
	fn: string;
	/** The arguments BY NAME, as declared in FunctionDefinition.params. */
	args: PropertyBag;
}

/** One comparison: a dictionary entry against a value. The reserved dict id "choice" is the exception — it reads the answers the player already gave IN THIS SCENE, which the engine tracks on its own. No project dictionary can be named that. */
export interface ConditionTest {
	/** The dictionary id, see DictionaryDefinition.id. "choice" is reserved: see Ports.Choice. */
	dict: string;
	/** The entry read in that dictionary. With dict "choice", a CHOICE block id of this scene. */
	entry: string;
	/** The comparison. */
	op: ConditionOperator;
	/** The right-hand side; its type follows the dictionary's valueType. With dict "choice", the Option.id the player picked. */
	value: PropertyValue;
	/** Link with the comparison ABOVE. Absent on the first one. */
	join?: ConditionJoin;
}

/** One case of a condition block: the exit port, and what must hold for it. */
export interface ConditionCase {
	/** The exit port of this case (K1...), or the block's out when cases share one exit. */
	port: string;
	/** Absent = always true. Such a case makes every following case unreachable. */
	when?: ConditionTest[];
}

/** One answer of a choice block, a translated key in its own right. */
export interface Option {
	/** The option id, which is also its exit port (C1...). */
	id: string;
	/** The full i18n key of its text. */
	key: string;
	/** Its text by locale, when texts are exported. */
	text?: TextByLocale;
	/** Absent = always offered. */
	when?: ConditionTest[];
}

/** A node of the graph. type decides which optional fields are present. */
export interface Block {
	/** Identity RELATIVE to its scene (DIALOG-002): what links and Scene.start reference. */
	id: string;
	/** The full i18n key, as localization files carry it. */
	key: string;
	/** The readable name (its summary), when written. */
	label?: string;
	/** Readable names above the block, root first. Empty ones are skipped. */
	parentLabels?: string[];
	/** What the block is. */
	type: BlockType;
	/** Card ids of who speaks. Resolve them through Blueprints.cards. */
	actors?: string[];
	/** Card id of the emotion, when one is set. */
	emotion?: string;
	/** Only with emotion. */
	intensity?: number;
	/** The line by locale, dialogs only, when texts are exported. */
	text?: TextByLocale;
	/** The body of a note block: never translated, only when notes are exported. */
	body?: string;
	/** The team note on the block, only when notes are exported. */
	note?: string;
	/** Properties SET on the block, native and project-declared alike, by id. Ids never collide: a project property cannot take a native name. One native holds a LIST rather than a scalar: waitForBlocks, an array of block ids OF THIS SCENE the block waits for before it advances - the counterpart of isAsync. */
	props?: PropertyBag;
	/** Action blocks: what to run, in order. */
	calls?: ActionCall[];
	/** Condition blocks: the cases, in evaluation order. */
	cases?: ConditionCase[];
	/** Choice blocks: the answers, in display order. */
	options?: Option[];
	/** Outgoing wires. Absent when nothing leaves the block. */
	next?: Link[];
}

/** One scene: its blocks, and where it starts. */
export interface Scene {
	/** The scene path without the reserved namespace (acte1, chap1.acte1). */
	scene: string;
	/** The readable name of the scene, when written. */
	label?: string;
	/** The entry block id. Absent = the scene has no entry and cannot play. */
	start?: string;
	/** Every exported block of the scene. */
	blocks: Block[];
}

/** The whole file. One scene per file or all of them: the only difference between the two split modes. */
export interface Blueprints {
	/** Always lsde-blueprints. */
	format: "lsde-blueprints";
	/** The FORMAT version. Bumps only when this contract changes. */
	version: 1;
	/** Which software wrote the file. */
	generator: Generator;
	/** ISO 8601 instant of the export. */
	exportedAt: string;
	/** The project name. */
	project: string;
	/** Every locale of the project. */
	locales: string[];
	/** The locale that is written first. Empty when the project declares none. */
	referenceLocale: string;
	/** The declared vocabulary, whole, never trimmed to the exported scenes. */
	dictionaries: DictionaryDefinition[];
	/** The declared engine functions. */
	functions: FunctionDefinition[];
	/** The cards that blocks may cite. */
	cards: Card[];
	/** The scenes carried by this file. */
	scenes: Scene[];
}

export type EngineConformanceSceneBlueprints = Blueprints;
