# Auto-generated by LSDE. Do not edit manually.
# Identifiers used by Engine-Conformance-Scene.blueprints.json: scenes, blocks, options, cards, dictionaries and functions.
# Compare these constants to what the payload carries; never retype the strings.
class_name EngineConformanceSceneBlueprintIds

## Every scene of the payload, by its scene path.
class Scenes:
	## @start ACTION-001
	## @blocks 18
	const reactor_breach = "reactor_breach"

	## @start DIALOG-001
	## @blocks 4
	const docking_ring_brief = "docking_ring_brief"
## Every block id, grouped by scene. Ids are relative to their scene: next.to and start use them.
class Blocks:
	## @scene reactor_breach
	class reactor_breach:
		## @type note
		## @note Cette note n'a pas de port d'entrée : elle ne se joue jamais.
		## @key __blueprints__.reactor_breach.NOTE-001
		const NOTE_001 = "NOTE-001"

		## @type note
		## @note Deuxième note, sans aucun fil : deux notes suffisent à montrer qu'elles ne comptent pas dans le flux.
		## @key __blueprints__.reactor_breach.NOTE-002
		const NOTE_002 = "NOTE-002"

		## @type action
		## @start
		## @calls play_music, set_counter, write_flag
		## @next then -> DIALOG-002, catch -> DIALOG-001
		## @note Le réacteur monte depuis vingt minutes et personne n'a coupé la musique du pont.
		## @key __blueprints__.reactor_breach.ACTION-001
		const ACTION_001 = "ACTION-001"

		## @type dialog
		## @example No sound. Of course there is no sound.
		## @actors nora
		## @emotion suspicious x45
		## @next out -> DIALOG-002
		## @note Nora encaisse la panne sans s'arrêter. Elle n'a pas dormi depuis deux jours.
		## @key __blueprints__.reactor_breach.DIALOG-001
		const DIALOG_001 = "DIALOG-001"

		## @type dialog
		## @example Reactor deck.{|} The floor is warm through my boots.
		## @actors nora
		## @emotion neutral x20
		## @next out -> DIALOG-003
		## @note Première réplique de la scène. Nora descend seule, avant que Kael la rattrape.
		## @key __blueprints__.reactor_breach.DIALOG-002
		const DIALOG_002 = "DIALOG-002"

		## @type dialog
		## @example Someone has been down here. Recently.
		## @actors kael, nora
		## @emotion afraid x60
		## @next var2 -> DIALOG-005, out -> CHOICE-001, var1 -> DIALOG-011
		## @note Les deux le disent en même temps, et aucun des deux ne veut être celui qui a raison.
		## @key __blueprints__.reactor_breach.DIALOG-003
		const DIALOG_003 = "DIALOG-003"

		## @type dialog
		## @example Then tell me what I am looking at.
		## @actors nora
		## @emotion neutral x35
		## @next out -> DIALOG-012
		## @note Elle ne hausse pas le ton. C'est ce qui inquiète Kael.
		## @key __blueprints__.reactor_breach.DIALOG-005
		const DIALOG_005 = "DIALOG-005"

		## @type dialog
		## @example Do not say my name out loud.
		## @actors vesk
		## @emotion afraid x100
		## @next out -> DIALOG-008
		## @note Vesk se cache derrière le réservoir. Il ne parle que si le joueur l'a déjà croisé ailleurs.
		## @key __blueprints__.reactor_breach.DIALOG-007
		const DIALOG_007 = "DIALOG-007"

		## @type dialog
		## @example Everyone done? The {{i2}} is still on the panel.
		## @actors nora
		## @emotion neutral x25
		## @next out -> CHOICE-001
		## @note Nora attend que les deux autres se taisent avant de reprendre la main.
		## @key __blueprints__.reactor_breach.DIALOG-008
		const DIALOG_008 = "DIALOG-008"

		## @type choice
		## @actors nora
		## @emotion neutral x30
		## @options C1, C2, C3, C4
		## @next C1 -> COND-001, C2 -> COND-001, C3 -> ACTION-002, C4 -> COND-002
		## @note Le choix qui porte toute la scène : les conditions plus bas relisent ce que le joueur répond ici.
		## @key __blueprints__.reactor_breach.CHOICE-001
		const CHOICE_001 = "CHOICE-001"

		## @type condition
		## @next K1 -> ACTION-002, K2 -> COND-003, K3 -> DIALOG-009, default -> COND-002
		## @note Trois issues et un repli. Le troisième cas n'a aucune comparaison : il est toujours vrai.
		## @key __blueprints__.reactor_breach.COND-001
		const COND_001 = "COND-001"

		## @type condition
		## @next default -> DIALOG-010, out -> COND-003
		## @note Deux issues seulement : vrai ou repli. Trois comparaisons liées par ET puis OU.
		## @key __blueprints__.reactor_breach.COND-002
		const COND_002 = "COND-002"

		## @type condition
		## @next default -> DIALOG-009, out -> DIALOG-010
		## @note Relit ce que le joueur a répondu plus haut, sans qu'aucune variable n'ait été posée pour ça.
		## @key __blueprints__.reactor_breach.COND-003
		const COND_003 = "COND-003"

		## @type action
		## @calls set_switch, add_item, shake_camera, close_bulkhead, unlock_achievement
		## @next then -> COND-003, catch -> DIALOG-010
		## @note Cinq appels d'affilée, dont un sans le moindre paramètre.
		## @key __blueprints__.reactor_breach.ACTION-002
		const ACTION_002 = "ACTION-002"

		## @type dialog
		## @example We are going back up. Now.
		## @actors kael
		## @emotion angry x90
		## @next out -> DIALOG-002
		## @note Kael reprend le contrôle et renvoie tout le monde au début du pont.
		## @key __blueprints__.reactor_breach.DIALOG-009
		const DIALOG_009 = "DIALOG-009"

		## @type dialog
		## @example {:a2}That is enough for one shift. Seal {{#ui.hud.airlock_label}}.
		## @actors nora
		## @emotion joy x15
		## @note Dernière réplique : aucun fil ne part d'ici.
		## @key __blueprints__.reactor_breach.DIALOG-010
		const DIALOG_010 = "DIALOG-010"

		## @type dialog
		## @example Do not touch the coupling, {{@a2}}. I mean it.
		## @actors kael
		## @emotion angry x80
		## @next out -> DIALOG-012
		## @note Kael ment : il sait très bien ce qu'il y a derrière le couplage, il l'a vu au pont 3.
		## @key __blueprints__.reactor_breach.DIALOG-011
		const DIALOG_011 = "DIALOG-011"

		## @type dialog
		## @example Good morning. Today is the fourteenth of a month I no longer hold.
		## @actors oracle
		## @emotion neutral x5
		## @next out -> DIALOG-007
		## @note L'Oracle parle par-dessus les autres, sans attendre son tour.
		## @key __blueprints__.reactor_breach.DIALOG-012
		const DIALOG_012 = "DIALOG-012"
	## @scene docking_ring_brief
	class docking_ring_brief:
		## @type dialog
		## @start
		## @example {{#ui.hud.airlock_label}}.{|} Two minutes, {{@a1}}.
		## @actors nora
		## @emotion neutral x10
		## @next out -> CHOICE-001
		## @note Scène courte : elle existe surtout pour vérifier qu'un export séparé produit bien deux fichiers.
		## @key __blueprints__.docking_ring_brief.DIALOG-001
		const DIALOG_001 = "DIALOG-001"

		## @type choice
		## @actors nora
		## @options C1, C2, C3
		## @next C1 -> ACTION-001, C2 -> DIALOG-002, C3 -> DIALOG-001
		## @note Deux de ces réponses lisent leur texte dans une clé d'interface partagée, la troisième a la sienne.
		## @key __blueprints__.docking_ring_brief.CHOICE-001
		const CHOICE_001 = "CHOICE-001"

		## @type action
		## @calls set_switch, play_music
		## @next then -> DIALOG-002, catch -> DIALOG-002
		## @note Kael a déjà lancé la séquence avant qu'elle réponde.
		## @key __blueprints__.docking_ring_brief.ACTION-001
		const ACTION_001 = "ACTION-001"

		## @type dialog
		## @example Told you it would hold.
		## @actors kael
		## @emotion joy x55
		## @note Kael se donne raison alors qu'il n'en savait rien.
		## @key __blueprints__.docking_ring_brief.DIALOG-002
		const DIALOG_002 = "DIALOG-002"
## Every option id, grouped by scene then by choice block. An option id is also its exit port.
class Options:
	## @scene reactor_breach
	class reactor_breach:
		## @block CHOICE-001
		class CHOICE_001:
			## @example What did you see on deck three, {{@a1}}?
			## @key __blueprints__.reactor_breach.CHOICE-001.C1
			const C1 = "C1"

			## @example I am not going any further.
			## @key __blueprints__.reactor_breach.CHOICE-001.C2
			const C2 = "C2"

			## @example Name your price.
			## @conditional
			## @key __blueprints__.reactor_breach.CHOICE-001.C3
			const C3 = "C3"

			## @example (Say nothing and watch him.)
			## @conditional
			## @key __blueprints__.reactor_breach.CHOICE-001.C4
			const C4 = "C4"
	## @scene docking_ring_brief
	class docking_ring_brief:
		## @block CHOICE-001
		class CHOICE_001:
			## @example Yes
			## @key ui.common.yes
			const C1 = "C1"

			## @example No
			## @key ui.common.no
			const C2 = "C2"

			## @example Give me one more minute.
			## @conditional
			## @key __blueprints__.docking_ring_brief.CHOICE-001.C3
			const C3 = "C3"
## Every card the blocks may cite, under its game name. The value is the id that actors carries.
class Cards:
	## @name kael
	## @role characters
	const kael = "var1"

	## @name nora
	## @role characters
	const nora = "var2"

	## @name oracle
	## @role characters
	const oracle = "var3"

	## @name vesk
	## @role characters
	const vesk = "var4"

	## @name neutral
	## @role emotions
	const neutral = "var5"

	## @name angry
	## @role emotions
	const angry = "var6"

	## @name afraid
	## @role emotions
	const afraid = "var7"

	## @name joy
	## @role emotions
	const joy = "var8"

	## @name suspicious
	## @role emotions
	const suspicious = "var9"

	## @name reactor_deck
	## @role places
	const reactor_deck = "var10"

	## @name docking_ring
	## @role places
	const docking_ring = "var11"

	## @name plasma_cell
	## @role none
	const plasma_cell = "var12"

	## @name keycard
	## @role none
	const keycard = "var13"

	## @name ration
	## @role none
	const ration = "var14"
## Every dictionary id, as ConditionTest.dict cites it.
class Dictionaries:
	## @type boolean
	## @entries 5
	const switches = "switches"

	## @type number
	## @entries 4
	const variables = "variables"

	## @type number
	## @entries 3
	const items = "items"

	## @type string
	## @entries 3
	const flags = "flags"
## Every entry key, grouped by dictionary: what ConditionTest.entry cites.
class DictionaryEntries:
	## @dictionary switches
	## @type boolean
	class switches:
		const door_unlocked = "door_unlocked"
		const oracle_awake = "oracle_awake"
		const reactor_stable = "reactor_stable"
		const met_vesk = "met_vesk"
		const alarm_armed = "alarm_armed"
	## @dictionary variables
	## @type number
	class variables:
		const chapter = "chapter"
		const credits = "credits"
		const trust_kael = "trust_kael"
		const alarm_level = "alarm_level"
	## @dictionary items
	## @type number
	class items:
		const plasma_cell = "plasma_cell"
		const keycard = "keycard"
		const ration = "ration"
	## @dictionary flags
	## @type string
	class flags:
		const faction = "faction"
		const last_port = "last_port"
		const player_callsign = "player_callsign"
## Every engine function id, as ActionCall.fn names it.
class Functions:
	## @params track: string, fadeMs: number, loop: boolean
	const play_music = "play_music"

	## @params flag: dictionaryKey(switches), value: boolean
	const set_switch = "set_switch"

	## @params item: dictionaryKey(items), count: number
	const add_item = "add_item"

	## @params counter: dictionaryKey(variables), value: number
	const set_counter = "set_counter"

	## @params flag: dictionaryKey(flags), value: string
	const write_flag = "write_flag"

	## @params intensity: number, durationMs: number
	const shake_camera = "shake_camera"

	## @params id: string
	const unlock_achievement = "unlock_achievement"

	## @params (none)
	const close_bulkhead = "close_bulkhead"
## Every parameter name, grouped by function: the keys of ActionCall.args.
class FunctionParams:
	## @function play_music
	class play_music:
		## @type string
		const track = "track"

		## @type number
		const fadeMs = "fadeMs"

		## @type boolean
		const loop = "loop"
	## @function set_switch
	class set_switch:
		## @type dictionaryKey (switches)
		const flag = "flag"

		## @type boolean
		const value = "value"
	## @function add_item
	class add_item:
		## @type dictionaryKey (items)
		const item = "item"

		## @type number
		const count = "count"
	## @function set_counter
	class set_counter:
		## @type dictionaryKey (variables)
		const counter = "counter"

		## @type number
		const value = "value"
	## @function write_flag
	class write_flag:
		## @type dictionaryKey (flags)
		const flag = "flag"

		## @type string
		const value = "value"
	## @function shake_camera
	class shake_camera:
		## @type number
		const intensity = "intensity"

		## @type number
		const durationMs = "durationMs"
	## @function unlock_achievement
	class unlock_achievement:
		## @type string
		const id = "id"
	## @function close_bulkhead
	class close_bulkhead:
		pass
