<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
    <RootNamespace>LsdeDialogEngine.Newtonsoft.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
    <PackageReference Include="xunit" Version="2.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../Runtime/Newtonsoft/LsdeDialogEngine.Newtonsoft.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../../../blueprints/blueprint.json" Link="blueprint.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
