#pragma once
// Auto-generated by LSDE Blueprint Export — Enums

#include <string>

/**
 * Scene identifiers for type-safe access to blueprint scenes.
 * Use these constants to start or reference a specific dialogue sequence.
 * Each value maps to the scene's UUID — stable even if the scene is renamed.
 */
namespace LSDE_SCENES {
	/**
	 * @brief Scene: Flow-001
	 * 2 ACTION, 1 CHOICE, 1 CONDITION, 8 DIALOG
	 * Entry: `DIALOG-001`
	 * - Characters: `Boo`, `lia`
	 */
	constexpr const char* flow001 = "199c33e2-a4aa-44bb-8b70-16ce88824e82";

}

/**
 * Block identifiers for type-safe access to individual blocks within scenes.
 * Includes block types: DIALOG, CHOICE, CONDITION, ACTION, NOTE.
 * Use these to register callbacks or listeners on specific blocks.
 * Each value maps to the block's UUID — stable even if the block is renamed.
 */
namespace LSDE_BLOCKS {
	/**
	 * @brief 🟧[ACTION] ACTION-001
	 * - Scene: `Flow-001`
	 * - In: `DIALOG-002`
	 * - Out: `DIALOG-003`
	 * `moveCameraTo`(InterestPoint1)
	 * ---
	 * <image url="./_images/action.webp" />
	 */
	constexpr const char* flow001Action001 = "73fa0dce-df57-4040-b2d7-2db8dc5156c2";

	/**
	 * @brief 🟧[ACTION] ACTION-002
	 * - Scene: `Flow-001`
	 * - In: `DIALOG-003`
	 * - Out: `CONDITION-001`
	 * `moveCameraTo`(a1)
	 * ---
	 * <image url="./_images/action.webp" />
	 */
	constexpr const char* flow001Action002 = "fed6440c-1a2a-47f8-9e40-3dbf3ce25492";

	/**
	 * @brief ⬜[CHOICE] CHOICE-001
	 * - Scene: `Flow-001`
	 * - In: `DIALOG-005`
	 * - Out: `DIALOG-006`, `DIALOG-007`
	 * - Choices: `aidez`, `continuer`
	 * ---
	 * <image url="./_images/choice.webp" />
	 */
	constexpr const char* flow001Choice001 = "23e9aeda-e1db-4f8e-ae9f-afaf76786e95";

	/**
	 * @brief 🟪[CONDITION] CONDITION-001
	 * - Scene: `Flow-001`
	 * - In: `ACTION-002`
	 * - Out: `DIALOG-004`, `DIALOG-008`
	 * Case 0:
	 * `VariableGlobal.key1` = `1`
	 * Case 1:
	 * `VariableGlobal.key2` = `2`
	 * ---
	 * <image url="./_images/cond.webp" />
	 */
	constexpr const char* flow001Condition001 = "f80757d6-73c0-4160-8449-e494f5c485b7";

	/**
	 * @brief 🟦[DIALOG] DIALOG-001 (entry)
	 * "Salut , dit moi que fait tu la ?"
	 * - Characters: `lia`
	 * - Scene: `Flow-001`
	 * - Out: `DIALOG-002`
	 * ---
	 * <image url="./_images/dialog.webp" />
	 */
	constexpr const char* flow001Dialog001 = "f2402df4-0081-4663-9fce-6dca72e9ff77";

	/**
	 * @brief 🟦[DIALOG] DIALOG-002
	 * "Ha j'ai tres mal et jessai de me reposer , je me suis cogner a cette roche la bas !"
	 * - Scene: `Flow-001`
	 * - In: `DIALOG-001`
	 * - Out: `ACTION-001`
	 * ---
	 * <image url="./_images/dialog.webp" />
	 */
	constexpr const char* flow001Dialog002 = "c302b3a4-3433-4cf4-8402-a61e33ba1a84";

	/**
	 * @brief 🟦[DIALOG] DIALOG-003
	 * "> ces la roche etrange qui semble avoir blesser cette creature !"
	 * - Scene: `Flow-001`
	 * - In: `ACTION-001`
	 * - Out: `ACTION-002`
	 * ---
	 * <image url="./_images/dialog.webp" />
	 */
	constexpr const char* flow001Dialog003 = "157817bf-073e-4368-89de-52e295ffcecb";

	/**
	 * @brief 🟦[DIALOG] DIALOG-004
	 * "Je compatis a votre douleur ! miouw"
	 * - Characters: `Boo`
	 * - Scene: `Flow-001`
	 * - In: `CONDITION-001`
	 * - Out: `DIALOG-005`
	 * ---
	 * <image url="./_images/dialog.webp" />
	 */
	constexpr const char* flow001Dialog004 = "f6262aa9-6d90-46d1-a0fd-f9108ded43ff";

	/**
	 * @brief 🟦[DIALOG] DIALOG-005
	 * "Moi aussi"
	 * - Characters: `lia`
	 * - Scene: `Flow-001`
	 * - In: `DIALOG-004`
	 * - Out: `CHOICE-001`
	 * ---
	 * <image url="./_images/dialog.webp" />
	 */
	constexpr const char* flow001Dialog005 = "a458323a-d832-405f-8f47-9ca096d7eea6";

	/**
	 * @brief 🟦[DIALOG] DIALOG-006
	 * "venez je vais vous aider"
	 * - Characters: `lia`
	 * - Scene: `Flow-001`
	 * - In: `CHOICE-001`
	 * ---
	 * <image url="./_images/dialog.webp" />
	 */
	constexpr const char* flow001Dialog006 = "8994d27a-592b-4fe6-9311-754f6f7d491d";

	/**
	 * @brief 🟦[DIALOG] DIALOG-007
	 * "a la prochaine"
	 * - Characters: `lia`
	 * - Scene: `Flow-001`
	 * - In: `CHOICE-001`
	 * ---
	 * <image url="./_images/dialog.webp" />
	 */
	constexpr const char* flow001Dialog007 = "03773f48-310f-43e8-a7bb-1062f1c92d83";

	/**
	 * @brief 🟦[DIALOG] DIALOG-008
	 * "hehehe"
	 * - Characters: `Boo`
	 * - Scene: `Flow-001`
	 * - In: `CONDITION-001`
	 * ---
	 * <image url="./_images/dialog.webp" />
	 */
	constexpr const char* flow001Dialog008 = "80a3b47d-1262-4bb4-a520-915fc88f75ea";

}

/**
 * Choice item identifiers for type-safe access to individual player choices.
 * Each value maps to a choice item's UUID within a CHOICE block.
 * Use these for switch/case handling of specific player decisions.
 */
namespace LSDE_CHOICES {
	/**
	 * @brief ⬜[CHOICE_ITEM] aidez
	 * "aidez"
	 * - Scene: `Flow-001`
	 * - Parent: `CHOICE-001`
	 */
	/** @see LSDE_BLOCKS::flow001Choice001 */
	constexpr const char* flow001Aidez = "decb34ee-dbb8-4f94-b770-9d94f63a3eaf";

	/**
	 * @brief ⬜[CHOICE_ITEM] continuer
	 * "continuer"
	 * - Scene: `Flow-001`
	 * - Parent: `CHOICE-001`
	 */
	/** @see LSDE_BLOCKS::flow001Choice001 */
	constexpr const char* flow001Continuer = "bfc4d9f3-3315-4d8b-8fc9-17e867521126";

}
