/* Auto-generated by LSDE Blueprint Export — Enums */

/**
 * Scene identifiers for type-safe access to blueprint scenes.
 * Use these constants to start or reference a specific dialogue sequence.
 * Each value maps to the scene's UUID — stable even if the scene is renamed.
 */
export enum LSDE_SCENES {
	/**
	 * ### Scene: New Scene
	 * 1 ACTION, 2 CHOICE, 1 CONDITION, 3 DIALOG
	 * Entry: `DIALOG-001` ⭐
	 * - Emotions: `sad`
	 * - Characters: `Boo`, `Gruht Tyron`, `Svelt Moon`, `lia`
	 */
	newScene = '3e0110a5-49bb-46fe-884b-05ce106af4cd',
}

/**
 * Block identifiers for type-safe access to individual blocks within scenes.
 * Includes block types: DIALOG, CHOICE, CONDITION, ACTION, NOTE.
 * Use these to register callbacks or listeners on specific blocks.
 * Each value maps to the block's UUID — stable even if the block is renamed.
 */
export enum LSDE_BLOCKS {
	/**
	 * ### 🟧[ACTION] ACTION-001
	 * - Scene: `New Scene`
	 * - In: `CONDITION-001`
	 * `7908f59d-b97d-40ea-80f1-30c6f762e30d`(a, 2)
	 * ---
	 * <image url="./_images/action.webp" />
	 */
	newSceneAction001 = 'd72bcf6a-161b-4759-90dd-2ae10a58fdd3',
	/**
	 * ### ⬜[CHOICE] CHOICE-001
	 * - Characters: `lia`
	 * - Scene: `New Scene`
	 * - In: `DIALOG-001`
	 * - Out: `DIALOG-002`
	 * - Choices: `C1`, `C2`
	 * ---
	 * <image url="./_images/choice.webp" />
	 */
	newSceneChoice001 = '014f503a-6688-429d-a5fe-801cf33f2410',
	/**
	 * ### ⬜[CHOICE] CHOICE-002
	 * - Scene: `New Scene`
	 * - In: `DIALOG-002`
	 * - Out: `CONDITION-001`
	 * - Choices: `C1.1`, `C2.1`
	 * ---
	 * <image url="./_images/choice.webp" />
	 */
	newSceneChoice002 = '2b184947-49f9-4e57-8600-70b46e2cd0ba',
	/**
	 * ### 🟪[CONDITION] CONDITION-001
	 * - Scene: `New Scene`
	 * - In: `CHOICE-002`
	 * - Out: `ACTION-001`, `DIALOG-003`
	 * `choice:014f503a-6688-429d-a5fe-801cf33f2410` = `a0eee458-6ccc-4a23-bd36-0b3d1f73771e`
	 * `choice:2b184947-49f9-4e57-8600-70b46e2cd0ba` = `e306346e-6bcc-4564-8b19-e2ed28fabafe`
	 * ---
	 * <image url="./_images/cond.webp" />
	 */
	newSceneCondition001 = '4074b6c2-bfc8-44f1-9a29-cda529bf522a',
	/**
	 * ### 🟦[DIALOG] DIALOG-001 ⭐
	 * _"C2"_
	 * - Characters: `Gruht Tyron` (sad ×2), `Svelt Moon` (sad ×2), `lia` (sad ×2), `Boo` (sad ×2)
	 * - Scene: `New Scene`
	 * - Out: `CHOICE-001`
	 * ---
	 * <image url="./_images/dialog.webp" />
	 */
	newSceneDialog001 = '6462dab3-0eb4-4a2c-a505-407556441156',
	/**
	 * ### 🟦[DIALOG] DIALOG-002
	 * _"D2"_
	 * - Scene: `New Scene`
	 * - In: `CHOICE-001`
	 * - Out: `CHOICE-002`
	 * ---
	 * <image url="./_images/dialog.webp" />
	 */
	newSceneDialog002 = 'c66437af-54b7-4a75-9efa-713e983c145d',
	/**
	 * ### 🟦[DIALOG] DIALOG-003
	 * _"D5"_
	 * - Scene: `New Scene`
	 * - In: `CONDITION-001`
	 * ---
	 * <image url="./_images/dialog.webp" />
	 */
	newSceneDialog003 = 'dfc30c4c-a1aa-4e76-81b6-640bf447351b',
}

/**
 * Choice item identifiers for type-safe access to individual player choices.
 * Each value maps to a choice item's UUID within a CHOICE block.
 * Use these for switch/case handling of specific player decisions.
 */
export enum LSDE_CHOICES {
	/**
	 * ### ⬜[CHOICE_ITEM] C1
	 * _"C1"_
	 * - Scene: `New Scene`
	 * - Parent: `CHOICE-001`
	 */
	/** @see {@link LSDE_BLOCKS.newSceneChoice001} */
	newSceneC1 = '17e98de3-1690-4ca4-8ea5-8070c15b1fe1',
	/**
	 * ### ⬜[CHOICE_ITEM] C2
	 * _"C2"_
	 * - Scene: `New Scene`
	 * - Parent: `CHOICE-001`
	 */
	/** @see {@link LSDE_BLOCKS.newSceneChoice001} */
	newSceneC2 = 'a0eee458-6ccc-4a23-bd36-0b3d1f73771e',
	/**
	 * ### ⬜[CHOICE_ITEM] C1.1
	 * _"C1.1"_
	 * - Scene: `New Scene`
	 * - Parent: `CHOICE-002`
	 */
	/** @see {@link LSDE_BLOCKS.newSceneChoice002} */
	newSceneC11 = 'd16d21ea-ecf8-4172-aaa3-668df80e9853',
	/**
	 * ### ⬜[CHOICE_ITEM] C2.1
	 * _"C2.1"_
	 * - Scene: `New Scene`
	 * - Parent: `CHOICE-002`
	 */
	/** @see {@link LSDE_BLOCKS.newSceneChoice002} */
	newSceneC21 = 'e306346e-6bcc-4564-8b19-e2ed28fabafe',
}
