// Auto-generated by LSDE Blueprint Export — Types
using System;
using System.Collections.Generic;

/*
 * LSDE Blueprint Export — Quick Integration Guide
 * 
 * Data Flow: BlueprintExport → Scene[] → Block[] + Connection[]
 * 
 * Getting Started:
 * 1. Parse the export file into the BlueprintExport root structure
 * 2. For each scene, use entryBlockId to find the start block
 * 3. Execute the block based on its type:
 *    - DIALOG: Display text, resolve characters and emotions
 *    - CHOICE: Present options, filter by visibilityConditions
 *    - CONDITION: Evaluate condition groups in order — single group: true/false ports, multiple groups: case_0..N/default ports
 *    - ACTION: Execute actions using signatures to resolve actionId
 *    - NOTE: Skip (designer-only, not for runtime)
 * 4. Follow connections to the next block(s):
 *    - Match connection.fromId === currentBlock.uuid
 *    - For CHOICE: match connection.fromPort === selectedChoice.uuid
 *    - For CONDITION: single group → fromPort "true"/"false"; switch mode → fromPort "case_0".."case_N" or "default"
 * 5. Use dictionaries to resolve condition keys and action params
 * 6. Use signatures to understand action types and param definitions
 * 7. Repeat until no outgoing connections remain
 */

/// <summary>
/// Reference types exported from the LSDE project configuration.
/// These provide type-safe access to project-defined characters, dictionaries, and action signatures.
/// Map these to your engine&apos;s own types for compile-time validation.
/// </summary>

/// <summary>Characters defined in the project</summary>
public static class lsdeCharacter
{
	public const string a1 = "a1";
	public const string a2 = "a2";
	public const string a3 = "a3";
	public const string a4 = "a4";
	public const string a5 = "a5";
	public const string a6 = "a6";
	public const string a7 = "a7";
	public const string a8 = "a8";
	public const string a9 = "a9";
}

/// <summary>Dictionary: VariableGlobal (2 values)</summary>
public static class lsdeDictionaryVariableGlobal
{
	public const string key1 = "key1";
	public const string key2 = "key2";
}

/// <summary>Action signature IDs</summary>
public static class lsdeActionId
{
	public const string moveCameraTo = "moveCameraTo";
}

/// <summary>
/// Represents a directed connection between two blocks in the blueprint.
/// Connections define the dialogue flow by linking output ports of source blocks
/// to input ports of target blocks.
/// </summary>
[System.Serializable]
public class BlueprintConnection
{
	/// <summary>Unique identifier for this connection.</summary>
	public string id;
	/// <summary>UUID of the source block. See <see cref="LSDE_BLOCKS"/> in BlueprintEnums.</summary>
	public string fromId;
	/// <summary>UUID of the target block. See <see cref="LSDE_BLOCKS"/> in BlueprintEnums.</summary>
	public string toId;
	/// <summary>
	/// Output port identifier on the source block.
	/// Port IDs can indicate specific branches (choice index, condition result, etc.).
	/// </summary>
	public string fromPort;
	/// <summary>Input port identifier on the target block.</summary>
	public string toPort;
	/// <summary>
	/// Zero-based index of the output port on the source block.
	/// Provides a stable numeric reference independent of port UUIDs.
	/// For CHOICE blocks: index of the selected choice option.
	/// For CONDITION blocks: 0 = true branch, 1 = false branch.
	/// For DIALOG blocks with portPerCharacter: index of the character port.
	/// </summary>
	public int? fromPortIndex;
}

/// <summary>
/// A generic key-value property attached to a block.
/// Properties hold custom data defined by block type or plugin configuration.
/// </summary>
[System.Serializable]
public class BlockProperty
{
	/// <summary>Property name or identifier.</summary>
	public string key;
	/// <summary>Property value. Can be a string, number, or boolean.</summary>
	public object value;
}

/// <summary>
/// A condition evaluated to control dialogue flow or choice visibility.
/// Conditions test variables or game state against expected values
/// to determine which paths are available to the player.
/// </summary>
[System.Serializable]
public class ExportCondition
{
	/// <summary>Unique identifier for this condition.</summary>
	public string uuid;
	/// <summary>
	/// Variable or game state key to evaluate.
	/// References a value in your game&apos;s variable system.
	/// </summary>
	public string key;
	/// <summary>
	/// Logical chain operator when combining with other conditions.
	/// Use &quot;|&quot; for OR logic, &quot;&amp;&quot; for AND logic.
	/// </summary>
	public string chain;
	/// <summary>
	/// Comparison operator for evaluation.
	/// Common values: equals, not_equals, greater_than, less_than, contains.
	/// </summary>
	public string @operator;
	/// <summary>Expected value to compare against the resolved key.</summary>
	public string value;
}

/// <summary>
/// An action triggered during or after block execution.
/// Actions can modify game state, trigger events, set variables,
/// or invoke any custom behavior in your engine.
/// </summary>
[System.Serializable]
public class ExportAction
{
	/// <summary>Unique identifier for this action instance.</summary>
	public string uuid;
	/// <summary>UUID of the signature definition in the project.</summary>
	public string signatureUuid;
	/// <summary>Human-readable signature ID for mapping to your engine&apos;s action handlers.</summary>
	public string actionId;
	/// <summary>
	/// Ordered list of parameters for the action.
	/// Parameter types and count depend on the action type.
	/// </summary>
	public List<object> @params;
}

/// <summary>
/// A player choice or response option within a dialogue block.
/// Choices represent selectable options presented to the player,
/// each leading to a different branch in the dialogue flow.
/// </summary>
[System.Serializable]
public class ChoiceItem
{
	/// <summary>Unique identifier for this choice.</summary>
	public string uuid;
	/// <summary>
	/// Hierarchical key for localization lookup.
	/// Use this key to retrieve the localized choice text from your localization system.
	/// </summary>
	public string structureKey;
	/// <summary>
	/// Display label for editor reference.
	/// Useful for debugging or displaying choice identifiers in development tools.
	/// </summary>
	public string label;
	/// <summary>
	/// Localized text map for this choice: { locale -&gt; text }.
	/// Contains the translated choice text for each supported language.
	/// </summary>
	public Dictionary<string, string> dialogueText;
	/// <summary>
	/// Conditions that control whether this choice is visible to the player.
	/// If all conditions evaluate to true (or none are set), the choice is shown.
	/// Use this to create contextual choices based on game state or player progress.
	/// </summary>
	public List<ExportCondition> visibilityConditions;
}

/// <summary>
/// LSDE native properties configured by the narrative designer for this block.
/// These properties are separate from the user&apos;s custom dictionary.
/// See BlueprintBlock.userProperties for designer-defined custom data.
/// </summary>
[System.Serializable]
public class NativeProperties
{
	/// <summary>
	/// When true, this block should execute asynchronously without blocking
	/// the main dialogue flow or player actions.
	/// An async block should be executed in parallel from its input point.
	/// The parent block is responsible for running async children in parallel,
	/// while the async block maintains its own blocking flow with its non-async children.
	/// Example: an NPC shouting from afar during an ongoing conversation.
	/// </summary>
	public bool isAsync;
	/// <summary>
	/// Delay in seconds before this block executes.
	/// Can be used in synergy with async and blocking flows to create
	/// natural pacing and emotional timing.
	/// Example: a character pauses briefly before responding, creating a sense
	/// of reflection. Or in an async block, an event triggers after a timed delay.
	/// </summary>
	public float delay;
	/// <summary>
	/// Maximum execution time in seconds for this block.
	/// If the block has not completed within this duration,
	/// your engine may skip it or proceed to the next block.
	/// </summary>
	public float timeout;
	/// <summary>
	/// Debug flag for development and testing purposes.
	/// When true, your engine can log extra information or highlight
	/// this block visually during playback for debugging.
	/// </summary>
	public bool debug;
	/// <summary>
	/// When true, this dialog block creates separate output ports for each character.
	/// Allows branching the flow based on which character is speaking,
	/// enabling character-specific dialogue routing in your engine.
	/// </summary>
	public bool portPerCharacter;
	/// <summary>
	/// When true, skip this block if the referenced actor or character
	/// is not present in the current scene.
	/// Useful for optional dialogue that depends on character presence.
	/// </summary>
	public bool skipIfMissingActor;
	/// <summary>
	/// UUIDs of blocks that must have been visited before this block can progress.
	/// Enables synchronization of parallel async branches.
	/// The block will not call next() until ALL listed blocks appear in visitedBlocks.
	/// </summary>
	public List<string> waitForBlocks;
	/// <summary>
	/// When true, this block waits for explicit player input or an engine signal
	/// before proceeding. This is a passive flag — the engine does not interpret it;
	/// it is up to the game developer to decide how to handle it.
	/// </summary>
	public bool waitInput;
}

/// <summary>
/// A character (actor) assigned to a dialogue block.
/// Characters represent the speakers or participants in a dialogue exchange.
/// </summary>
[System.Serializable]
public class BlockCharacter
{
	/// <summary>UUID of the character variable in the project.</summary>
	public string uuid;
	/// <summary>Short identifier (tag) assigned in Character Configuration.</summary>
	public string id;
	/// <summary>Character display name as defined in the project&apos;s character variables.</summary>
	public string name;
	/// <summary>
	/// Emotion label assigned to this character in this dialogue block.
	/// Represents the character&apos;s emotional state during this dialogue.
	/// Values are project-defined (e.g. happy, angry, sad, neutral).
	/// </summary>
	public string emotion;
	/// <summary>
	/// Intensity of the assigned emotion, on a project-defined scale.
	/// Higher values indicate stronger emotional expression.
	/// </summary>
	public float? emotionIntensity;
}

/// <summary>A screenshot or image captured from the editor for documentation.</summary>
[System.Serializable]
public class BlockScreenshot
{
	/// <summary>Image source as a data URL (base64) or file path.</summary>
	public string src;
	/// <summary>Optional caption or description for this screenshot.</summary>
	public string note;
}

/// <summary>
/// Non-logic metadata for display and organizational purposes.
/// Metadata should not contain anything that affects your game&apos;s code logic.
/// It provides notes, visual hints, and categorization that can optionally
/// be rendered in your engine&apos;s UI or development tools.
/// </summary>
[System.Serializable]
public class BlockMetadata
{
	/// <summary>
	/// Visual color coding (hex format) assigned by the designer.
	/// Can be used to render block highlights or categories in your UI.
	/// </summary>
	public string color;
	/// <summary>
	/// Free-form designer notes attached to this block.
	/// Intended for internal documentation, not displayed to players.
	/// </summary>
	public string comments;
	/// <summary>
	/// Contextual tags for categorization and filtering.
	/// Can be used for searching, filtering, or conditional logic in your tools.
	/// </summary>
	public List<string> tags;
	/// <summary>
	/// Screenshots or images captured from the editor for this block.
	/// Useful for documentation or visual reference in development tools.
	/// </summary>
	public List<BlockScreenshot> screenShots;
	/// <summary>
	/// Characters (actors) assigned to this block.
	/// Each character includes name, optional portrait image, emotion, and intensity.
	/// </summary>
	public List<BlockCharacter> characters;
	/// <summary>
	/// Additional designer-defined metadata key-value pairs.
	/// Contains arbitrary data not covered by standard metadata fields.
	/// </summary>
	public Dictionary<string, object> others;
}

/// <summary>
/// Common properties shared by all blueprint block types.
/// Use the &quot;type&quot; field to determine the specific block type and access type-specific fields.
/// </summary>
// For polymorphic JSON deserialization, add [JsonDerivedType] attributes
[System.Serializable]
public class BlueprintBlock
{
	/// <summary>Unique block identifier. See <see cref="LSDE_BLOCKS"/> in BlueprintEnums.</summary>
	public string uuid;
	/// <summary>
	/// Block type determining behavior and rendering.
	/// Values: DIALOG, CHOICE, CONDITION, ACTION, NOTE.
	/// </summary>
	public string type;
	/// <summary>
	/// Display label or name assigned in the editor.
	/// Useful for debugging and identifying blocks in development tools.
	/// </summary>
	public string label;
	/// <summary>
	/// Hierarchy of parent folder labels providing structural context.
	/// Represents the path from root to this block in the dialogue tree.
	/// </summary>
	public List<string> parentLabels;
	/// <summary>
	/// Array of custom key-value properties defined by block configuration.
	/// See BlockProperty for the key-value structure.
	/// </summary>
	public List<BlockProperty> properties;
	/// <summary>
	/// User-defined custom properties dictionary.
	/// Contains arbitrary data set by the narrative designer for game-specific needs.
	/// Keys and values are project-specific and not controlled by LSDE.
	/// </summary>
	public Dictionary<string, string> userProperties;
	/// <summary>
	/// LSDE native execution properties for this block.
	/// See NativeProperties for detailed descriptions.
	/// </summary>
	public NativeProperties nativeProperties;
	/// <summary>
	/// Non-logic metadata for display and organizational purposes.
	/// See BlockMetadata for details.
	/// </summary>
	public BlockMetadata metadata;
	/// <summary>
	/// When true, this block is the entry point of the scene&apos;s dialogue flow.
	/// Start traversing the dialogue graph from this block.
	/// Only one block per scene should have this flag set.
	/// </summary>
	public bool isStartBlock;
}

/// <summary>
/// A dialogue block displaying text spoken by a character.
/// Contains a structure key for localization lookup and optional localized text.
/// </summary>
[System.Serializable]
public class DialogBlock : BlueprintBlock
{
	/// <summary>
	/// Hierarchical key for tree navigation and localization lookup.
	/// Use this key to resolve localized text from your localization system.
	/// </summary>
	public string structureKey;
	/// <summary>
	/// Raw text content of the block.
	/// For DIALOG blocks, this is the dialogue text in the primary language.
	/// </summary>
	public string content;
	/// <summary>
	/// Localized text map: { locale -&gt; text }.
	/// Contains the translated dialogue text for each supported language.
	/// </summary>
	public Dictionary<string, string> dialogueText;
}

/// <summary>
/// A choice block presenting selectable options to the player.
/// Contains a list of choice items, each with optional visibility conditions.
/// </summary>
[System.Serializable]
public class ChoiceBlock : BlueprintBlock
{
	/// <summary>
	/// Available player choices or response options.
	/// Only present on CHOICE-type blocks.
	/// </summary>
	public List<ChoiceItem> choices;
	/// <summary>
	/// Designer note attached to this block.
	/// Internal documentation, not intended for player-facing display.
	/// </summary>
	public string note;
}

/// <summary>
/// A condition block that evaluates logic to branch the dialogue flow.
/// With a single condition group: has true/false output ports.
/// With multiple groups (switch mode): each group is a case evaluated in order,
/// first matching case routes to its port (case_0, case_1, ...), otherwise routes to default.
/// </summary>
[System.Serializable]
public class ConditionBlock : BlueprintBlock
{
	/// <summary>
	/// 2D array of condition groups (Condition[][]).
	/// Each inner array is a &quot;case&quot; — conditions chained with &amp; (AND) / | (OR).
	/// Groups are evaluated in order: first matching group wins.
	/// Single group: classic true/false branching. Multiple groups: switch mode.
	/// </summary>
	public List<List<ExportCondition>> conditions;
	/// <summary>
	/// Designer note attached to this block.
	/// Internal documentation, not intended for player-facing display.
	/// </summary>
	public string note;
}

/// <summary>
/// An action block that triggers game state changes or events.
/// Contains a list of actions to execute during or after the block runs.
/// </summary>
[System.Serializable]
public class ActionBlock : BlueprintBlock
{
	/// <summary>
	/// Actions triggered during or after this block&apos;s execution.
	/// Can modify game state, trigger events, or invoke custom behavior.
	/// </summary>
	public List<ExportAction> actions;
	/// <summary>
	/// Designer note attached to this block.
	/// Internal documentation, not intended for player-facing display.
	/// </summary>
	public string note;
}

/// <summary>
/// A designer note block for documentation purposes.
/// Not executed at runtime — used for internal documentation only.
/// </summary>
[System.Serializable]
public class NoteBlock : BlueprintBlock { }

/// <summary>
/// A scene containing a group of related dialogue blocks and their connections.
/// Scenes organize the dialogue blueprint into logical sections,
/// each with its own set of blocks, connections, and flow.
/// </summary>
[System.Serializable]
public class BlueprintScene
{
	/// <summary>Unique scene identifier. See <see cref="LSDE_SCENES"/> in BlueprintEnums.</summary>
	public string uuid;
	/// <summary>Scene name or label assigned by the designer.</summary>
	public string label;
	/// <summary>
	/// Scene-level notes from the designer.
	/// Internal documentation providing context about the scene&apos;s purpose.
	/// </summary>
	public string note;
	/// <summary>Scene creation or last modification date.</summary>
	public string date;
	/// <summary>UUID of the entry block. See <see cref="LSDE_BLOCKS"/> in BlueprintEnums.</summary>
	public string entryBlockId;
	/// <summary>All blocks (nodes) contained within this scene.</summary>
	public List<BlueprintBlock> blocks;
	/// <summary>All connections between blocks defining the dialogue flow in this scene.</summary>
	public List<BlueprintConnection> connections;
}

/// <summary>
/// A single entry in a dictionary group.
/// Dictionary rows define the valid keys that can be used in conditions and actions.
/// </summary>
[System.Serializable]
public class DictionaryRow
{
	/// <summary>
	/// The key identifier for this dictionary entry.
	/// Referenced in conditions and action parameters.
	/// </summary>
	public string key;
}

/// <summary>
/// A dictionary group defining reusable key-value pairs for conditions and actions.
/// Dictionaries provide the valid keys that can be referenced in condition evaluations
/// and action parameters of type &quot;dictionary&quot;.
/// </summary>
[System.Serializable]
public class ExportDictionary
{
	/// <summary>Unique identifier for this dictionary group.</summary>
	public string uuid;
	/// <summary>
	/// Identifier for this dictionary group.
	/// Used as prefix in condition keys (e.g. &quot;groupId.rowKey&quot;).
	/// </summary>
	public string id;
	/// <summary>
	/// All entries in this dictionary group.
	/// See DictionaryRow for the entry structure.
	/// </summary>
	public List<DictionaryRow> rows;
}

/// <summary>
/// Available options when type is &quot;enum&quot;.
/// Each option has an id (value) and optional display label.
/// </summary>
[System.Serializable]
public class EnumOption
{
	/// <summary>Unique value identifier for this option.</summary>
	public string id;
	/// <summary>Display label for this option.</summary>
	public string label;
}

/// <summary>
/// A parameter definition for an action signature.
/// Describes the expected type and constraints for an action parameter.
/// </summary>
[System.Serializable]
public class SignatureParam
{
	/// <summary>Display label for this parameter.</summary>
	public string label;
	/// <summary>
	/// Data type of this parameter.
	/// Values: &quot;boolean&quot;, &quot;string&quot;, &quot;number&quot;, &quot;enum&quot;, &quot;dictionary&quot;.
	/// </summary>
	public string type;
	/// <summary>
	/// UUID of the dictionary group this parameter references.
	/// Only present when type is &quot;dictionary&quot;.
	/// </summary>
	public string dictionaryGroupUuid;
	/// <summary>
	/// Available options when type is &quot;enum&quot;.
	/// Each option has an id (value) and optional display label.
	/// </summary>
	public List<EnumOption> enumOptions;
}

/// <summary>
/// An action signature defining a reusable action type in the blueprint system.
/// Signatures describe what an action does and what parameters it expects.
/// Map the signature id to your engine&apos;s action handlers.
/// </summary>
[System.Serializable]
public class ActionSignature
{
	/// <summary>
	/// Unique identifier for this signature.
	/// Referenced by ExportAction.actionId to link actions to their definitions.
	/// </summary>
	public string uuid;
	/// <summary>
	/// Short identifier for this action type.
	/// Use this to map to your engine&apos;s action handler system.
	/// </summary>
	public string id;
	/// <summary>
	/// Parameter definitions describing the expected inputs for this action.
	/// See SignatureParam for the parameter structure.
	/// </summary>
	public List<SignatureParam> @params;
}

/// <summary>
/// Root container for the exported blueprint data.
/// Contains all scenes, dictionaries, action signatures, and export metadata.
/// </summary>
[System.Serializable]
public class BlueprintExport
{
	/// <summary>
	/// Schema version of this export format.
	/// Use this to detect format changes and ensure compatibility.
	/// </summary>
	public string version;
	/// <summary>ISO 8601 timestamp of when this export was generated.</summary>
	public string exportDate;
	/// <summary>Name of the LSDE project that generated this export.</summary>
	public string projectName;
	/// <summary>Primary language locale code for the project (e.g. &quot;fr&quot;, &quot;en&quot;).</summary>
	public string primaryLanguage;
	/// <summary>All language locale codes included in this export.</summary>
	public List<string> locales;
	/// <summary>
	/// Dictionary groups defining valid keys for conditions and action parameters.
	/// See Dictionary for the group structure.
	/// </summary>
	public List<ExportDictionary> dictionaries;
	/// <summary>
	/// Action signature definitions describing available action types.
	/// See ActionSignature for the signature structure.
	/// </summary>
	public List<ActionSignature> signatures;
	/// <summary>
	/// All exported scenes containing dialogue blocks and connections.
	/// See BlueprintScene for the scene structure.
	/// </summary>
	public List<BlueprintScene> scenes;
}
