#pragma once
// Auto-generated by LSDE Blueprint Export — Types

#include <string>
#include <vector>
#include <variant>
#include <optional>
#include <unordered_map>

/*
 * LSDE Blueprint Export — Quick Integration Guide
 * 
 * Data Flow: BlueprintExport → Scene[] → Block[] + Connection[]
 * 
 * Getting Started:
 * 1. Parse the export file into the BlueprintExport root structure
 * 2. For each scene, use entryBlockId to find the start block
 * 3. Execute the block based on its type:
 *    - DIALOG: Display text, resolve characters and emotions
 *    - CHOICE: Present options, filter by visibilityConditions
 *    - CONDITION: Evaluate conditions, follow true/false port (index 0/1)
 *    - ACTION: Execute actions using signatures to resolve actionId
 *    - NOTE: Skip (designer-only, not for runtime)
 * 4. Follow connections to the next block(s):
 *    - Match connection.fromId === currentBlock.uuid
 *    - For CHOICE: match connection.fromPort === selectedChoice.uuid
 *    - For CONDITION: fromPortIndex 0 = true, 1 = false
 * 5. Use dictionaries to resolve condition keys and action params
 * 6. Use signatures to understand action types and param definitions
 * 7. Repeat until no outgoing connections remain
 */

/**
 * Reference types exported from the LSDE project configuration.
 * These provide type-safe access to project-defined characters, dictionaries, and action signatures.
 * Map these to your engine's own types for compile-time validation.
 */

/** @brief Characters defined in the project */
namespace lsdeCharacter {
	constexpr const char* a1 = "a1";
	constexpr const char* a2 = "a2";
	constexpr const char* a3 = "a3";
	constexpr const char* a4 = "a4";
	constexpr const char* a5 = "a5";
	constexpr const char* a6 = "a6";
	constexpr const char* a7 = "a7";
	constexpr const char* a8 = "a8";
	constexpr const char* a9 = "a9";
}

/** @brief Dictionary: GroupName (2 values) */
namespace lsdeDictionaryGroupName {
	constexpr const char* key1 = "key1";
	constexpr const char* key2 = "key2";
}

/** @brief Action signature IDs */
namespace lsdeActionId {
	constexpr const char* signatureID1 = "signatureID1";
}

/**
 * Represents a directed connection between two blocks in the blueprint.
 * Connections define the dialogue flow by linking output ports of source blocks
 * to input ports of target blocks.
 */
struct BlueprintConnection {
	/** @brief Unique identifier for this connection. */
	std::string id;
	/** @brief UUID of the source block. @see LSDE_BLOCKS in BlueprintEnums.h */
	std::string fromId;
	/** @brief UUID of the target block. @see LSDE_BLOCKS in BlueprintEnums.h */
	std::string toId;
	/**
	 * Output port identifier on the source block.
	 * Port IDs can indicate specific branches (choice index, condition result, etc.).
	 */
	std::string fromPort;
	/** @brief Input port identifier on the target block. */
	std::string toPort;
	/**
	 * Zero-based index of the output port on the source block.
	 * Provides a stable numeric reference independent of port UUIDs.
	 * For CHOICE blocks: index of the selected choice option.
	 * For CONDITION blocks: 0 = true branch, 1 = false branch.
	 * For DIALOG blocks with portPerCharacter: index of the character port.
	 */
	std::optional<int> fromPortIndex;
};

/**
 * A generic key-value property attached to a block.
 * Properties hold custom data defined by block type or plugin configuration.
 */
struct BlockProperty {
	/** @brief Property name or identifier. */
	std::string key;
	/** @brief Property value. Can be a string, number, or boolean. */
	std::string value;
};

/**
 * A condition evaluated to control dialogue flow or choice visibility.
 * Conditions test variables or game state against expected values
 * to determine which paths are available to the player.
 */
struct ExportCondition {
	/** @brief Unique identifier for this condition. */
	std::string uuid;
	/**
	 * Variable or game state key to evaluate.
	 * References a value in your game's variable system.
	 */
	std::string key;
	/**
	 * Logical chain operator when combining with other conditions.
	 * Use "|" for OR logic, "&" for AND logic.
	 */
	std::string chain;
	/**
	 * Comparison operator for evaluation.
	 * Common values: equals, not_equals, greater_than, less_than, contains.
	 */
	std::string operator_;
	/** @brief Expected value to compare against the resolved key. */
	std::string value;
};

/**
 * An action triggered during or after block execution.
 * Actions can modify game state, trigger events, set variables,
 * or invoke any custom behavior in your engine.
 */
struct ExportAction {
	/** @brief Unique identifier for this action instance. */
	std::string uuid;
	/** @brief UUID of the signature definition in the project. */
	std::string signatureUuid;
	/** @brief Human-readable signature ID for mapping to your engine's action handlers. */
	std::string actionId;
	/**
	 * Ordered list of parameters for the action.
	 * Parameter types and count depend on the action type.
	 */
	std::vector<std::string> params;
};

/**
 * A player choice or response option within a dialogue block.
 * Choices represent selectable options presented to the player,
 * each leading to a different branch in the dialogue flow.
 */
struct ChoiceItem {
	/** @brief Unique identifier for this choice. */
	std::string uuid;
	/**
	 * Hierarchical key for localization lookup.
	 * Use this key to retrieve the localized choice text from your localization system.
	 */
	std::string structureKey;
	/**
	 * Display label for editor reference.
	 * Useful for debugging or displaying choice identifiers in development tools.
	 */
	std::string label;
	/**
	 * Localized text map for this choice: { locale -> text }.
	 * Contains the translated choice text for each supported language.
	 */
	std::unordered_map<std::string, std::string> dialogueText;
	/**
	 * Conditions that control whether this choice is visible to the player.
	 * If all conditions evaluate to true (or none are set), the choice is shown.
	 * Use this to create contextual choices based on game state or player progress.
	 */
	std::vector<ExportCondition> visibilityConditions;
};

/**
 * LSDE native properties configured by the narrative designer for this block.
 * These properties are separate from the user's custom dictionary.
 * See BlueprintBlock.userProperties for designer-defined custom data.
 */
struct NativeProperties {
	/**
	 * When true, this block should execute asynchronously without blocking
	 * the main dialogue flow or player actions.
	 * An async block should be executed in parallel from its input point.
	 * The parent block is responsible for running async children in parallel,
	 * while the async block maintains its own blocking flow with its non-async children.
	 * Example: an NPC shouting from afar during an ongoing conversation.
	 */
	bool isAsync = false;
	/**
	 * Delay in seconds before this block executes.
	 * Can be used in synergy with async and blocking flows to create
	 * natural pacing and emotional timing.
	 * Example: a character pauses briefly before responding, creating a sense
	 * of reflection. Or in an async block, an event triggers after a timed delay.
	 */
	float delay = 0.0f;
	/**
	 * Maximum execution time in seconds for this block.
	 * If the block has not completed within this duration,
	 * your engine may skip it or proceed to the next block.
	 */
	float timeout = 0.0f;
	/**
	 * Debug flag for development and testing purposes.
	 * When true, your engine can log extra information or highlight
	 * this block visually during playback for debugging.
	 */
	bool debug = false;
	/**
	 * When true, this dialog block creates separate output ports for each character.
	 * Allows branching the flow based on which character is speaking,
	 * enabling character-specific dialogue routing in your engine.
	 */
	bool portPerCharacter = false;
	/**
	 * When true, skip this block if the referenced actor or character
	 * is not present in the current scene.
	 * Useful for optional dialogue that depends on character presence.
	 */
	bool skipIfMissingActor = false;
	/**
	 * UUIDs of blocks that must have been visited before this block can progress.
	 * Enables synchronization of parallel async branches.
	 * The block will not call next() until ALL listed blocks appear in visitedBlocks.
	 */
	std::vector<std::string> waitForBlocks;
	/**
	 * When true, this block waits for explicit player input or an engine signal
	 * before proceeding. This is a passive flag — the engine does not interpret it;
	 * it is up to the game developer to decide how to handle it.
	 */
	bool waitInput = false;
};

/**
 * A character (actor) assigned to a dialogue block.
 * Characters represent the speakers or participants in a dialogue exchange.
 */
struct BlockCharacter {
	/** @brief UUID of the character variable in the project. */
	std::string uuid;
	/** @brief Short identifier (tag) assigned in Character Configuration. */
	std::string id;
	/** @brief Character display name as defined in the project's character variables. */
	std::string name;
	/**
	 * Emotion label assigned to this character in this dialogue block.
	 * Represents the character's emotional state during this dialogue.
	 * Values are project-defined (e.g. happy, angry, sad, neutral).
	 */
	std::string emotion;
	/**
	 * Intensity of the assigned emotion, on a project-defined scale.
	 * Higher values indicate stronger emotional expression.
	 */
	std::optional<float> emotionIntensity;
};

/** @brief A screenshot or image captured from the editor for documentation. */
struct BlockScreenshot {
	/** @brief Image source as a data URL (base64) or file path. */
	std::string src;
	/** @brief Optional caption or description for this screenshot. */
	std::string note;
};

/**
 * Non-logic metadata for display and organizational purposes.
 * Metadata should not contain anything that affects your game's code logic.
 * It provides notes, visual hints, and categorization that can optionally
 * be rendered in your engine's UI or development tools.
 */
struct BlockMetadata {
	/**
	 * Visual color coding (hex format) assigned by the designer.
	 * Can be used to render block highlights or categories in your UI.
	 */
	std::string color;
	/**
	 * Free-form designer notes attached to this block.
	 * Intended for internal documentation, not displayed to players.
	 */
	std::string comments;
	/**
	 * Contextual tags for categorization and filtering.
	 * Can be used for searching, filtering, or conditional logic in your tools.
	 */
	std::vector<std::string> tags;
	/**
	 * Screenshots or images captured from the editor for this block.
	 * Useful for documentation or visual reference in development tools.
	 */
	std::vector<BlockScreenshot> screenShots;
	/**
	 * Characters (actors) assigned to this block.
	 * Each character includes name, optional portrait image, emotion, and intensity.
	 */
	std::vector<BlockCharacter> characters;
	/**
	 * Additional designer-defined metadata key-value pairs.
	 * Contains arbitrary data not covered by standard metadata fields.
	 */
	std::unordered_map<std::string, std::string> others;
};

/**
 * Common properties shared by all blueprint block types.
 * Use the "type" field to determine the specific block type and access type-specific fields.
 */
struct BlueprintBlockBase {
	/** @brief Unique block identifier. @see LSDE_BLOCKS in BlueprintEnums.h */
	std::string uuid;
	/**
	 * Block type determining behavior and rendering.
	 * Values: DIALOG, CHOICE, CONDITION, ACTION, NOTE.
	 */
	std::string type;
	/**
	 * Display label or name assigned in the editor.
	 * Useful for debugging and identifying blocks in development tools.
	 */
	std::string label;
	/**
	 * Hierarchy of parent folder labels providing structural context.
	 * Represents the path from root to this block in the dialogue tree.
	 */
	std::vector<std::string> parentLabels;
	/**
	 * Array of custom key-value properties defined by block configuration.
	 * See BlockProperty for the key-value structure.
	 */
	std::vector<BlockProperty> properties;
	/**
	 * User-defined custom properties dictionary.
	 * Contains arbitrary data set by the narrative designer for game-specific needs.
	 * Keys and values are project-specific and not controlled by LSDE.
	 */
	std::unordered_map<std::string, std::string> userProperties;
	/**
	 * LSDE native execution properties for this block.
	 * See NativeProperties for detailed descriptions.
	 */
	NativeProperties nativeProperties;
	/**
	 * Non-logic metadata for display and organizational purposes.
	 * See BlockMetadata for details.
	 */
	BlockMetadata metadata;
	/**
	 * When true, this block is the entry point of the scene's dialogue flow.
	 * Start traversing the dialogue graph from this block.
	 * Only one block per scene should have this flag set.
	 */
	bool isStartBlock = false;
	virtual ~BlueprintBlockBase() = default;
};

/**
 * A dialogue block displaying text spoken by a character.
 * Contains a structure key for localization lookup and optional localized text.
 */
struct DialogBlock : public BlueprintBlockBase {
	/**
	 * Hierarchical key for tree navigation and localization lookup.
	 * Use this key to resolve localized text from your localization system.
	 */
	std::string structureKey;
	/**
	 * Raw text content of the block.
	 * For DIALOG blocks, this is the dialogue text in the primary language.
	 */
	std::string content;
	/**
	 * Localized text map: { locale -> text }.
	 * Contains the translated dialogue text for each supported language.
	 */
	std::unordered_map<std::string, std::string> dialogueText;
};

/**
 * A choice block presenting selectable options to the player.
 * Contains a list of choice items, each with optional visibility conditions.
 */
struct ChoiceBlock : public BlueprintBlockBase {
	/**
	 * Available player choices or response options.
	 * Only present on CHOICE-type blocks.
	 */
	std::vector<ChoiceItem> choices;
	/**
	 * Designer note attached to this block.
	 * Internal documentation, not intended for player-facing display.
	 */
	std::string note;
};

/**
 * A condition block that evaluates logic to branch the dialogue flow.
 * Has true/false output ports based on condition evaluation.
 */
struct ConditionBlock : public BlueprintBlockBase {
	/**
	 * Conditions evaluated before this block executes.
	 * If conditions are not met, the block may be skipped or hidden.
	 */
	std::vector<ExportCondition> conditions;
	/**
	 * Designer note attached to this block.
	 * Internal documentation, not intended for player-facing display.
	 */
	std::string note;
};

/**
 * An action block that triggers game state changes or events.
 * Contains a list of actions to execute during or after the block runs.
 */
struct ActionBlock : public BlueprintBlockBase {
	/**
	 * Actions triggered during or after this block's execution.
	 * Can modify game state, trigger events, or invoke custom behavior.
	 */
	std::vector<ExportAction> actions;
	/**
	 * Designer note attached to this block.
	 * Internal documentation, not intended for player-facing display.
	 */
	std::string note;
};

/**
 * A designer note block for documentation purposes.
 * Not executed at runtime — used for internal documentation only.
 */
struct NoteBlock : public BlueprintBlockBase {};

/**
 * Represents a single block (node) in the dialogue blueprint.
 * Each block has a type that determines its behavior:
 * DIALOG (dialogue text), CHOICE (player choices), CONDITION (branching logic),
 * ACTION (game state changes), NOTE (designer notes, not executed).
 */
using BlueprintBlock = std::variant<DialogBlock, ChoiceBlock, ConditionBlock, ActionBlock, NoteBlock>;

/**
 * A scene containing a group of related dialogue blocks and their connections.
 * Scenes organize the dialogue blueprint into logical sections,
 * each with its own set of blocks, connections, and flow.
 */
struct BlueprintScene {
	/** @brief Unique scene identifier. @see LSDE_SCENES in BlueprintEnums.h */
	std::string uuid;
	/** @brief Scene name or label assigned by the designer. */
	std::string label;
	/**
	 * Scene-level notes from the designer.
	 * Internal documentation providing context about the scene's purpose.
	 */
	std::string note;
	/** @brief Scene creation or last modification date. */
	std::string date;
	/** @brief UUID of the entry block. @see LSDE_BLOCKS in BlueprintEnums.h */
	std::string entryBlockId;
	/** @brief All blocks (nodes) contained within this scene. */
	std::vector<BlueprintBlock> blocks;
	/** @brief All connections between blocks defining the dialogue flow in this scene. */
	std::vector<BlueprintConnection> connections;
};

/**
 * A single entry in a dictionary group.
 * Dictionary rows define the valid keys that can be used in conditions and actions.
 */
struct DictionaryRow {
	/**
	 * The key identifier for this dictionary entry.
	 * Referenced in conditions and action parameters.
	 */
	std::string key;
};

/**
 * A dictionary group defining reusable key-value pairs for conditions and actions.
 * Dictionaries provide the valid keys that can be referenced in condition evaluations
 * and action parameters of type "dictionary".
 */
struct ExportDictionary {
	/** @brief Unique identifier for this dictionary group. */
	std::string uuid;
	/**
	 * Short identifier for this dictionary group.
	 * Used as prefix in condition keys (e.g. "groupId.rowKey").
	 */
	std::string id;
	/**
	 * All entries in this dictionary group.
	 * See DictionaryRow for the entry structure.
	 */
	std::vector<DictionaryRow> rows;
};

/** @brief An option in an enum parameter. */
struct EnumOption {
	std::string id;
	std::string label;
};

/**
 * A parameter definition for an action signature.
 * Describes the expected type and constraints for an action parameter.
 */
struct SignatureParam {
	/** @brief Display label for this parameter. */
	std::string label;
	/**
	 * Data type of this parameter.
	 * Values: "boolean", "string", "number", "enum", "dictionary".
	 */
	std::string type;
	/**
	 * UUID of the dictionary group this parameter references.
	 * Only present when type is "dictionary".
	 */
	std::string dictionaryGroupUuid;
	/**
	 * Available options when type is "enum".
	 * Each option has an id (value) and optional display label.
	 */
	std::vector<EnumOption> enumOptions;
};

/**
 * An action signature defining a reusable action type in the blueprint system.
 * Signatures describe what an action does and what parameters it expects.
 * Map the signature id to your engine's action handlers.
 */
struct ActionSignature {
	/**
	 * Unique identifier for this signature.
	 * Referenced by ExportAction.actionId to link actions to their definitions.
	 */
	std::string uuid;
	/**
	 * Short identifier for this action type.
	 * Use this to map to your engine's action handler system.
	 */
	std::string id;
	/**
	 * Parameter definitions describing the expected inputs for this action.
	 * See SignatureParam for the parameter structure.
	 */
	std::vector<SignatureParam> params;
};

/**
 * Root container for the exported blueprint data.
 * Contains all scenes, dictionaries, action signatures, and export metadata.
 */
struct BlueprintExport {
	/**
	 * Schema version of this export format.
	 * Use this to detect format changes and ensure compatibility.
	 */
	std::string version;
	/** @brief ISO 8601 timestamp of when this export was generated. */
	std::string exportDate;
	/** @brief Name of the LSDE project that generated this export. */
	std::string projectName;
	/** @brief Primary language locale code for the project (e.g. "fr", "en"). */
	std::string primaryLanguage;
	/** @brief All language locale codes included in this export. */
	std::vector<std::string> locales;
	/**
	 * Dictionary groups defining valid keys for conditions and action parameters.
	 * See Dictionary for the group structure.
	 */
	std::vector<ExportDictionary> dictionaries;
	/**
	 * Action signature definitions describing available action types.
	 * See ActionSignature for the signature structure.
	 */
	std::vector<ActionSignature> signatures;
	/**
	 * All exported scenes containing dialogue blocks and connections.
	 * See BlueprintScene for the scene structure.
	 */
	std::vector<BlueprintScene> scenes;
};
