// Auto-generated by LSDE Blueprint Export — Enums

/// <summary>
/// Scene identifiers for type-safe access to blueprint scenes.
/// Use these constants to start or reference a specific dialogue sequence.
/// Each value maps to the scene&apos;s UUID — stable even if the scene is renamed.
/// </summary>
public static class LSDE_SCENES
{
	/// <summary>
	/// <para>Scene: New Scene</para>
	/// <para>1 ACTION, 1 CHOICE, 1 CONDITION, 5 DIALOG</para>
	/// <para>Entry: <c>DIALOG-001</c></para>
	/// <para>Emotions: <c>sad</c></para>
	/// <para>Characters: <c>Boo</c>, <c>Gigi Jinx </c>, <c>Gruht Tyron</c>, <c>Lulu Star</c>, <c>Salomon Sky</c>, <c>Svelt Moon</c>, <c>lia</c></para>
	/// </summary>
	/// <remarks>
	/// <image url="./_images/char_gruht_tyron_0.png" />
	/// <image url="./_images/char_gigi_jinx__1.png" />
	/// <image url="./_images/char_lulu_star_2.png" />
	/// <image url="./_images/char_boo_3.png" />
	/// <image url="./_images/char_svelt_moon_4.png" />
	/// <image url="./_images/char_salomon_sky_5.png" />
	/// <image url="./_images/char_lia_6.png" />
	/// </remarks>
	public const string newScene = "3e0110a5-49bb-46fe-884b-05ce106af4cd";

}

/// <summary>
/// Block identifiers for type-safe access to individual blocks within scenes.
/// Includes block types: DIALOG, CHOICE, CONDITION, ACTION, NOTE.
/// Use these to register callbacks or listeners on specific blocks.
/// Each value maps to the block&apos;s UUID — stable even if the block is renamed.
/// </summary>
public static class LSDE_BLOCKS
{
	/// <summary>
	/// <para>🟧[ACTION] ACTION-001</para>
	/// <para>Scene: <c>New Scene</c></para>
	/// <para>In: <c>DIALOG-001</c></para>
	/// <para>Out: <c>DIALOG-002</c>, <c>DIALOG-005</c></para>
	/// </summary>
	/// <remarks>
	/// <image url="./_images/action.webp" />
	/// </remarks>
	public const string newSceneAction001 = "b1e1cf07-e8d2-42cc-b1ec-7cfb21b6a3aa";

	/// <summary>
	/// <para>⬜[CHOICE] CHOICE-001</para>
	/// <para>Characters: <c>Gruht Tyron</c>, <c>Gigi Jinx </c>, <c>Lulu Star</c>, <c>Boo</c>, <c>Svelt Moon</c>, <c>Salomon Sky</c></para>
	/// <para>Scene: <c>New Scene</c></para>
	/// <para>In: <c>DIALOG-001</c></para>
	/// <para>Out: <c>CONDITION-001</c>, <c>DIALOG-001</c></para>
	/// </summary>
	/// <remarks>
	/// <image url="./_images/choice.webp" />
	/// <image url="./_images/char_gruht_tyron_0.png" />
	/// <image url="./_images/char_gigi_jinx__1.png" />
	/// <image url="./_images/char_lulu_star_2.png" />
	/// <image url="./_images/char_boo_3.png" />
	/// <image url="./_images/char_svelt_moon_4.png" />
	/// <image url="./_images/char_salomon_sky_5.png" />
	/// </remarks>
	public const string newSceneChoice001 = "014f503a-6688-429d-a5fe-801cf33f2410";

	/// <summary>
	/// <para>🟪[CONDITION] CONDITION-001</para>
	/// <para>Scene: <c>New Scene</c></para>
	/// <para>In: <c>DIALOG-002</c>, <c>CHOICE-001</c></para>
	/// <para>Out: <c>DIALOG-003</c>, <c>DIALOG-004</c></para>
	/// </summary>
	/// <remarks>
	/// <image url="./_images/cond.webp" />
	/// </remarks>
	public const string newSceneCondition001 = "85f4640b-9c6e-4940-9bc6-b4d12847d5f8";

	/// <summary>
	/// <para>🟦[DIALOG] DIALOG-001 (entry)</para>
	/// <para>"choice2"</para>
	/// <para>Characters: <c>Gruht Tyron</c> (sad x2), <c>Svelt Moon</c> (sad x2), <c>lia</c> (sad x2), <c>Boo</c> (sad x2)</para>
	/// <para>Scene: <c>New Scene</c></para>
	/// <para>In: <c>CHOICE-001</c></para>
	/// <para>Out: <c>CHOICE-001</c>, <c>ACTION-001</c>, <c>DIALOG-005</c></para>
	/// </summary>
	/// <remarks>
	/// <image url="./_images/dialog.webp" />
	/// <image url="./_images/char_gruht_tyron_0.png" />
	/// <image url="./_images/char_svelt_moon_1.png" />
	/// <image url="./_images/char_lia_2.png" />
	/// <image url="./_images/char_boo_3.png" />
	/// </remarks>
	public const string newSceneDialog001 = "6462dab3-0eb4-4a2c-a505-407556441156";

	/// <summary>
	/// <para>🟦[DIALOG] DIALOG-002</para>
	/// <para>"text 2"</para>
	/// <para>Characters: <c>lia</c></para>
	/// <para>Scene: <c>New Scene</c></para>
	/// <para>In: <c>ACTION-001</c></para>
	/// <para>Out: <c>CONDITION-001</c></para>
	/// </summary>
	/// <remarks>
	/// <image url="./_images/dialog.webp" />
	/// <image url="./_images/char_lia_0.png" />
	/// </remarks>
	public const string newSceneDialog002 = "df23757c-a35a-4bcb-8056-e7ad232eff1d";

	/// <summary>
	/// <para>🟦[DIALOG] DIALOG-003</para>
	/// <para>"text 3"</para>
	/// <para>Scene: <c>New Scene</c></para>
	/// <para>In: <c>CONDITION-001</c></para>
	/// </summary>
	/// <remarks>
	/// <image url="./_images/dialog.webp" />
	/// </remarks>
	public const string newSceneDialog003 = "bccf5542-80f1-4415-b0c4-24ff4a638aa7";

	/// <summary>
	/// <para>🟦[DIALOG] DIALOG-004</para>
	/// <para>"text 3.2"</para>
	/// <para>Scene: <c>New Scene</c></para>
	/// <para>In: <c>CONDITION-001</c>, <c>DIALOG-005</c></para>
	/// </summary>
	/// <remarks>
	/// <image url="./_images/dialog.webp" />
	/// </remarks>
	public const string newSceneDialog004 = "0c524a39-6bbe-468f-8876-43c1fbb2a030";

	/// <summary>
	/// <para>🟦[DIALOG] DIALOG-005</para>
	/// <para>"action fail"</para>
	/// <para>Scene: <c>New Scene</c></para>
	/// <para>In: <c>ACTION-001</c>, <c>DIALOG-001</c></para>
	/// <para>Out: <c>DIALOG-004</c></para>
	/// </summary>
	/// <remarks>
	/// <image url="./_images/dialog.webp" />
	/// </remarks>
	public const string newSceneDialog005 = "9b47c43c-4b06-4e37-bec6-2ee2597d4bae";

}

/// <summary>
/// Choice item identifiers for type-safe access to individual player choices.
/// Each value maps to a choice item&apos;s UUID within a CHOICE block.
/// Use these for switch/case handling of specific player decisions.
/// </summary>
public static class LSDE_CHOICES
{
	/// <summary>
	/// <para>⬜[CHOICE_ITEM] choice1</para>
	/// <para>"choice1"</para>
	/// <para>Scene: <c>New Scene</c></para>
	/// </summary>
	/// <summary>See <see cref="LSDE_BLOCKS.newSceneChoice001"/></summary>
	public const string newSceneChoice1 = "17e98de3-1690-4ca4-8ea5-8070c15b1fe1";

	/// <summary>
	/// <para>⬜[CHOICE_ITEM] choice2</para>
	/// <para>"choice2"</para>
	/// <para>Scene: <c>New Scene</c></para>
	/// </summary>
	/// <summary>See <see cref="LSDE_BLOCKS.newSceneChoice001"/></summary>
	public const string newSceneChoice2 = "a0eee458-6ccc-4a23-bd36-0b3d1f73771e";

}
