// Auto-generated by LSDE Blueprint Export — Enums

/// <summary>
/// Scene identifiers for type-safe access to blueprint scenes.
/// Use these constants to start or reference a specific dialogue sequence.
/// Each value maps to the scene&apos;s UUID — stable even if the scene is renamed.
/// </summary>
public static class LSDE_SCENES
{
	/// <summary>
	/// <para>Scene: New Scene</para>
	/// <para>1 ACTION, 2 CHOICE, 1 CONDITION, 8 DIALOG</para>
	/// <para>Entry: <c>DIALOG-001</c></para>
	/// <para>Emotions: <c>sad</c></para>
	/// <para>Characters: <c>Boo</c>, <c>Gruht Tyron</c>, <c>Svelt Moon</c>, <c>Zoozo Zee</c>, <c>lia</c></para>
	/// </summary>
	public const string newScene = "3e0110a5-49bb-46fe-884b-05ce106af4cd";

}

/// <summary>
/// Block identifiers for type-safe access to individual blocks within scenes.
/// Includes block types: DIALOG, CHOICE, CONDITION, ACTION, NOTE.
/// Use these to register callbacks or listeners on specific blocks.
/// Each value maps to the block&apos;s UUID — stable even if the block is renamed.
/// </summary>
public static class LSDE_BLOCKS
{
	/// <summary>
	/// <para>🟧[ACTION] ACTION-001</para>
	/// <para>Scene: <c>New Scene</c></para>
	/// <para>In: <c>CONDITION-001</c></para>
	/// </summary>
	/// <remarks>
	/// <image url="./_images/action.webp" />
	/// </remarks>
	public const string newSceneAction001 = "d72bcf6a-161b-4759-90dd-2ae10a58fdd3";

	/// <summary>
	/// <para>⬜[CHOICE] CHOICE-001</para>
	/// <para>Characters: <c>lia</c></para>
	/// <para>Scene: <c>New Scene</c></para>
	/// <para>In: <c>DIALOG-001</c></para>
	/// <para>Out: <c>DIALOG-002</c>, <c>DIALOG-004</c></para>
	/// </summary>
	/// <remarks>
	/// <image url="./_images/choice.webp" />
	/// </remarks>
	public const string newSceneChoice001 = "014f503a-6688-429d-a5fe-801cf33f2410";

	/// <summary>
	/// <para>⬜[CHOICE] CHOICE-002</para>
	/// <para>Scene: <c>New Scene</c></para>
	/// <para>In: <c>DIALOG-002</c></para>
	/// <para>Out: <c>CONDITION-001</c></para>
	/// </summary>
	/// <remarks>
	/// <image url="./_images/choice.webp" />
	/// </remarks>
	public const string newSceneChoice002 = "2b184947-49f9-4e57-8600-70b46e2cd0ba";

	/// <summary>
	/// <para>🟪[CONDITION] CONDITION-001</para>
	/// <para>Scene: <c>New Scene</c></para>
	/// <para>In: <c>CHOICE-002</c></para>
	/// <para>Out: <c>ACTION-001</c>, <c>DIALOG-003</c></para>
	/// </summary>
	/// <remarks>
	/// <image url="./_images/cond.webp" />
	/// </remarks>
	public const string newSceneCondition001 = "4074b6c2-bfc8-44f1-9a29-cda529bf522a";

	/// <summary>
	/// <para>🟦[DIALOG] DIALOG-001 (entry)</para>
	/// <para>"C2"</para>
	/// <para>Characters: <c>lia</c> (sad x2), <c>Boo</c> (sad x2), <c>Svelt Moon</c> (sad x2), <c>Gruht Tyron</c> (sad x2)</para>
	/// <para>Scene: <c>New Scene</c></para>
	/// <para>Out: <c>CHOICE-001</c></para>
	/// </summary>
	/// <remarks>
	/// <image url="./_images/dialog.webp" />
	/// </remarks>
	public const string newSceneDialog001 = "6462dab3-0eb4-4a2c-a505-407556441156";

	/// <summary>
	/// <para>🟦[DIALOG] DIALOG-002</para>
	/// <para>"D2"</para>
	/// <para>Scene: <c>New Scene</c></para>
	/// <para>In: <c>CHOICE-001</c></para>
	/// <para>Out: <c>CHOICE-002</c></para>
	/// </summary>
	/// <remarks>
	/// <image url="./_images/dialog.webp" />
	/// </remarks>
	public const string newSceneDialog002 = "c66437af-54b7-4a75-9efa-713e983c145d";

	/// <summary>
	/// <para>🟦[DIALOG] DIALOG-003</para>
	/// <para>"D5"</para>
	/// <para>Scene: <c>New Scene</c></para>
	/// <para>In: <c>CONDITION-001</c></para>
	/// </summary>
	/// <remarks>
	/// <image url="./_images/dialog.webp" />
	/// </remarks>
	public const string newSceneDialog003 = "dfc30c4c-a1aa-4e76-81b6-640bf447351b";

	/// <summary>
	/// <para>🟦[DIALOG] DIALOG-004</para>
	/// <para>"Hehehe!"</para>
	/// <para>Characters: <c>Gruht Tyron</c></para>
	/// <para>Scene: <c>New Scene</c></para>
	/// <para>In: <c>CHOICE-001</c></para>
	/// <para>Out: <c>DIALOG-005</c>, <c>DIALOG-006</c></para>
	/// </summary>
	/// <remarks>
	/// <image url="./_images/dialog.webp" />
	/// </remarks>
	public const string newSceneDialog004 = "4a800564-098f-4b88-a36b-f5d03f642944";

	/// <summary>
	/// <para>🟦[DIALOG] DIALOG-005</para>
	/// <para>"Je suis le roi!"</para>
	/// <para>Characters: <c>Gruht Tyron</c></para>
	/// <para>Scene: <c>New Scene</c></para>
	/// <para>In: <c>DIALOG-004</c></para>
	/// <para>Out: <c>DIALOG-008</c></para>
	/// </summary>
	/// <remarks>
	/// <image url="./_images/dialog.webp" />
	/// </remarks>
	public const string newSceneDialog005 = "2a087cbc-3b00-457a-9448-538e39a475ab";

	/// <summary>
	/// <para>🟦[DIALOG] DIALOG-006</para>
	/// <para>"heu, je suis pas certain de comprendre"</para>
	/// <para>Characters: <c>Zoozo Zee</c></para>
	/// <para>Scene: <c>New Scene</c></para>
	/// <para>In: <c>DIALOG-004</c></para>
	/// <para>Out: <c>DIALOG-007</c></para>
	/// </summary>
	/// <remarks>
	/// <image url="./_images/dialog.webp" />
	/// </remarks>
	public const string newSceneDialog006 = "ef7301d9-c8ce-4416-9a28-4b1f5595ac74";

	/// <summary>
	/// <para>🟦[DIALOG] DIALOG-007</para>
	/// <para>"heu non mais ca va pas !? ces moi qui est las"</para>
	/// <para>Characters: <c>Zoozo Zee</c></para>
	/// <para>Scene: <c>New Scene</c></para>
	/// <para>In: <c>DIALOG-006</c></para>
	/// </summary>
	/// <remarks>
	/// <image url="./_images/dialog.webp" />
	/// </remarks>
	public const string newSceneDialog007 = "d0cf7ee4-8dcb-4b75-b373-5d4a1dca73be";

	/// <summary>
	/// <para>🟦[DIALOG] DIALOG-008</para>
	/// <para>"ces pas moi le probleme !!!"</para>
	/// <para>Characters: <c>Gruht Tyron</c></para>
	/// <para>Scene: <c>New Scene</c></para>
	/// <para>In: <c>DIALOG-005</c></para>
	/// </summary>
	/// <remarks>
	/// <image url="./_images/dialog.webp" />
	/// </remarks>
	public const string newSceneDialog008 = "7ab18c86-c98e-41f1-99ca-51c7e66cb144";

}

/// <summary>
/// Choice item identifiers for type-safe access to individual player choices.
/// Each value maps to a choice item&apos;s UUID within a CHOICE block.
/// Use these for switch/case handling of specific player decisions.
/// </summary>
public static class LSDE_CHOICES
{
	/// <summary>
	/// <para>⬜[CHOICE_ITEM] C1</para>
	/// <para>"C1"</para>
	/// <para>Scene: <c>New Scene</c></para>
	/// </summary>
	/// <summary>See <see cref="LSDE_BLOCKS.newSceneChoice001"/></summary>
	public const string newSceneC1 = "17e98de3-1690-4ca4-8ea5-8070c15b1fe1";

	/// <summary>
	/// <para>⬜[CHOICE_ITEM] C2</para>
	/// <para>"C2"</para>
	/// <para>Scene: <c>New Scene</c></para>
	/// </summary>
	/// <summary>See <see cref="LSDE_BLOCKS.newSceneChoice001"/></summary>
	public const string newSceneC2 = "a0eee458-6ccc-4a23-bd36-0b3d1f73771e";

	/// <summary>
	/// <para>⬜[CHOICE_ITEM] C1.1</para>
	/// <para>"C1.1"</para>
	/// <para>Scene: <c>New Scene</c></para>
	/// </summary>
	/// <summary>See <see cref="LSDE_BLOCKS.newSceneChoice002"/></summary>
	public const string newSceneC11 = "d16d21ea-ecf8-4172-aaa3-668df80e9853";

	/// <summary>
	/// <para>⬜[CHOICE_ITEM] C2.1</para>
	/// <para>"C2.1"</para>
	/// <para>Scene: <c>New Scene</c></para>
	/// </summary>
	/// <summary>See <see cref="LSDE_BLOCKS.newSceneChoice002"/></summary>
	public const string newSceneC21 = "e306346e-6bcc-4564-8b19-e2ed28fabafe";

}
