// Auto-generated by LSDE. Do not edit manually.
// Identifiers used by Engine-Conformance-Scene.blueprints.json: scenes, blocks, options, cards, dictionaries and functions.
// Compare these constants to what the payload carries; never retype the strings.

export const EngineConformanceSceneBlueprintIds = {
	/**
	 * Every scene of the payload. The name comes from its path, the VALUE is the id that survives a
	 * rename - store that one wherever a scene is referenced from outside the payload.
	 */
	Scenes: {
		/**
		 * @scene reactor_breach
		 * @start ACTION-001
		 * @blocks 18
		 */
		reactor_breach: "sc_u0vqg2g8",

		/**
		 * @scene docking_ring_brief
		 * @start DIALOG-001
		 * @blocks 4
		 */
		docking_ring_brief: "sc_xx7wop3t",
	},

	/** Every block id, grouped by scene. Ids are relative to their scene: next.to and start use them. */
	Blocks: {
		/** @scene reactor_breach */
		reactor_breach: {
			/**
			 * @type note
			 * @note Cette note n'a pas de port d'entrée : elle ne se joue jamais.
			 * @key __blueprints__.reactor_breach.NOTE-001
			 */
			NOTE_001: "NOTE-001",

			/**
			 * @type note
			 * @note Deuxième note, sans aucun fil : deux notes suffisent à montrer qu'elles ne comptent pas dans le flux.
			 * @key __blueprints__.reactor_breach.NOTE-002
			 */
			NOTE_002: "NOTE-002",

			/**
			 * @type action
			 * @start
			 * @calls play_music, set_counter, write_flag
			 * @next then -> DIALOG-002, catch -> DIALOG-001
			 * @note Le réacteur monte depuis vingt minutes et personne n'a coupé la musique du pont.
			 * @key __blueprints__.reactor_breach.ACTION-001
			 */
			ACTION_001: "ACTION-001",

			/**
			 * @type dialog
			 * @example No sound. Of course there is no sound.
			 * @actors nora
			 * @emotion suspicious x45
			 * @next out -> DIALOG-002
			 * @note Nora encaisse la panne sans s'arrêter. Elle n'a pas dormi depuis deux jours.
			 * @key __blueprints__.reactor_breach.DIALOG-001
			 */
			DIALOG_001: "DIALOG-001",

			/**
			 * @type dialog
			 * @example Reactor deck.{|} The floor is warm through my boots.
			 * @actors nora
			 * @emotion neutral x20
			 * @next out -> DIALOG-003
			 * @note Première réplique de la scène. Nora descend seule, avant que Kael la rattrape.
			 * @key __blueprints__.reactor_breach.DIALOG-002
			 */
			DIALOG_002: "DIALOG-002",

			/**
			 * @type dialog
			 * @example Someone has been down here. Recently.
			 * @actors kael, nora
			 * @emotion afraid x60
			 * @next var2 -> DIALOG-005, out -> CHOICE-001, var1 -> DIALOG-011
			 * @note Les deux le disent en même temps, et aucun des deux ne veut être celui qui a raison.
			 * @key __blueprints__.reactor_breach.DIALOG-003
			 */
			DIALOG_003: "DIALOG-003",

			/**
			 * @type dialog
			 * @example Then tell me what I am looking at.
			 * @actors nora
			 * @emotion neutral x35
			 * @next out -> DIALOG-012
			 * @note Elle ne hausse pas le ton. C'est ce qui inquiète Kael.
			 * @key __blueprints__.reactor_breach.DIALOG-005
			 */
			DIALOG_005: "DIALOG-005",

			/**
			 * @type dialog
			 * @example Do not say my name out loud.
			 * @actors vesk
			 * @emotion afraid x100
			 * @next out -> DIALOG-008
			 * @note Vesk se cache derrière le réservoir. Il ne parle que si le joueur l'a déjà croisé ailleurs.
			 * @key __blueprints__.reactor_breach.DIALOG-007
			 */
			DIALOG_007: "DIALOG-007",

			/**
			 * @type dialog
			 * @example Everyone done? The {{i2}} is still on the panel.
			 * @actors nora
			 * @emotion neutral x25
			 * @next out -> CHOICE-001
			 * @note Nora attend que les deux autres se taisent avant de reprendre la main.
			 * @key __blueprints__.reactor_breach.DIALOG-008
			 */
			DIALOG_008: "DIALOG-008",

			/**
			 * @type choice
			 * @actors nora
			 * @emotion neutral x30
			 * @options C1, C2, C3, C4
			 * @next C1 -> COND-001, C2 -> COND-001, C3 -> ACTION-002, C4 -> COND-002
			 * @note Le choix qui porte toute la scène : les conditions plus bas relisent ce que le joueur répond ici.
			 * @key __blueprints__.reactor_breach.CHOICE-001
			 */
			CHOICE_001: "CHOICE-001",

			/**
			 * @type condition
			 * @next K1 -> ACTION-002, K3 -> DIALOG-009, default -> COND-002, K2 -> COND-004
			 * @note Trois issues et un repli. Le troisième cas n'a aucune comparaison : il est toujours vrai.
			 * @key __blueprints__.reactor_breach.COND-001
			 */
			COND_001: "COND-001",

			/**
			 * @type condition
			 * @next default -> DIALOG-010, out -> COND-004
			 * @note Deux issues seulement : vrai ou repli. Trois comparaisons liées par ET puis OU.
			 * @key __blueprints__.reactor_breach.COND-002
			 */
			COND_002: "COND-002",

			/**
			 * @type action
			 * @calls set_switch, add_item, shake_camera, close_bulkhead, unlock_achievement
			 * @next catch -> DIALOG-010, then -> COND-004
			 * @note Cinq appels d'affilée, dont un sans le moindre paramètre.
			 * @key __blueprints__.reactor_breach.ACTION-002
			 */
			ACTION_002: "ACTION-002",

			/**
			 * @type dialog
			 * @example We are going back up. Now.
			 * @actors kael
			 * @emotion angry x90
			 * @next out -> DIALOG-002
			 * @note Kael reprend le contrôle et renvoie tout le monde au début du pont.
			 * @key __blueprints__.reactor_breach.DIALOG-009
			 */
			DIALOG_009: "DIALOG-009",

			/**
			 * @type dialog
			 * @example {:a2}That is enough for one shift. Seal {{#ui.hud.airlock_label}}.
			 * @actors nora
			 * @emotion joy x15
			 * @note Dernière réplique : aucun fil ne part d'ici.
			 * @key __blueprints__.reactor_breach.DIALOG-010
			 */
			DIALOG_010: "DIALOG-010",

			/**
			 * @type dialog
			 * @example Do not touch the coupling, {{@a2}}. I mean it.
			 * @actors kael
			 * @emotion angry x80
			 * @next out -> DIALOG-012
			 * @note Kael ment : il sait très bien ce qu'il y a derrière le couplage, il l'a vu au pont 3.
			 * @key __blueprints__.reactor_breach.DIALOG-011
			 */
			DIALOG_011: "DIALOG-011",

			/**
			 * @type dialog
			 * @example Good morning. Today is the fourteenth of a month I no longer hold.
			 * @actors oracle
			 * @emotion neutral x5
			 * @next out -> DIALOG-007
			 * @note L'Oracle parle par-dessus les autres, sans attendre son tour.
			 * @key __blueprints__.reactor_breach.DIALOG-012
			 */
			DIALOG_012: "DIALOG-012",

			/**
			 * @type condition
			 * @next out -> DIALOG-010, default -> DIALOG-009
			 * @note Relit ce que le joueur a répondu plus haut, sans qu'aucune variable n'ait été posée pour ça.
			 * @key __blueprints__.reactor_breach.COND-004
			 */
			COND_004: "COND-004",
		},

		/** @scene docking_ring_brief */
		docking_ring_brief: {
			/**
			 * @type dialog
			 * @start
			 * @example {{#ui.hud.airlock_label}}.{|} Two minutes, {{@a1}}.
			 * @actors nora
			 * @emotion neutral x10
			 * @next out -> CHOICE-001
			 * @note Scène courte : elle existe surtout pour vérifier qu'un export séparé produit bien deux fichiers.
			 * @key __blueprints__.docking_ring_brief.DIALOG-001
			 */
			DIALOG_001: "DIALOG-001",

			/**
			 * @type choice
			 * @actors nora
			 * @options C1, C2, C3
			 * @next C1 -> ACTION-001, C2 -> DIALOG-002, C3 -> DIALOG-001
			 * @note Deux de ces réponses lisent leur texte dans une clé d'interface partagée, la troisième a la sienne.
			 * @key __blueprints__.docking_ring_brief.CHOICE-001
			 */
			CHOICE_001: "CHOICE-001",

			/**
			 * @type action
			 * @calls set_switch, play_music
			 * @next then -> DIALOG-002, catch -> DIALOG-002
			 * @note Kael a déjà lancé la séquence avant qu'elle réponde.
			 * @key __blueprints__.docking_ring_brief.ACTION-001
			 */
			ACTION_001: "ACTION-001",

			/**
			 * @type dialog
			 * @example Told you it would hold.
			 * @actors kael
			 * @emotion joy x55
			 * @note Kael se donne raison alors qu'il n'en savait rien.
			 * @key __blueprints__.docking_ring_brief.DIALOG-002
			 */
			DIALOG_002: "DIALOG-002",
		},
	},

	/** Every option id, grouped by scene then by choice block. An option id is also its exit port. */
	Options: {
		/** @scene reactor_breach */
		reactor_breach: {
			/** @block CHOICE-001 */
			CHOICE_001: {
				/**
				 * @example What did you see on deck three, {{@a1}}?
				 * @key __blueprints__.reactor_breach.CHOICE-001.C1
				 */
				C1: "C1",

				/**
				 * @example I am not going any further.
				 * @key __blueprints__.reactor_breach.CHOICE-001.C2
				 */
				C2: "C2",

				/**
				 * @example Name your price.
				 * @conditional
				 * @key __blueprints__.reactor_breach.CHOICE-001.C3
				 */
				C3: "C3",

				/**
				 * @example (Say nothing and watch him.)
				 * @conditional
				 * @key __blueprints__.reactor_breach.CHOICE-001.C4
				 */
				C4: "C4",
			},
		},

		/** @scene docking_ring_brief */
		docking_ring_brief: {
			/** @block CHOICE-001 */
			CHOICE_001: {
				/**
				 * @example Yes
				 * @key ui.common.yes
				 */
				C1: "C1",

				/**
				 * @example No
				 * @key ui.common.no
				 */
				C2: "C2",

				/**
				 * @example Give me one more minute.
				 * @conditional
				 * @key __blueprints__.docking_ring_brief.CHOICE-001.C3
				 */
				C3: "C3",
			},
		},
	},

	/** Every card the blocks may cite, under its game name. The value is the id that actors carries. */
	Cards: {
		/**
		 * @name kael
		 * @role characters
		 */
		kael: "var1",

		/**
		 * @name nora
		 * @role characters
		 */
		nora: "var2",

		/**
		 * @name oracle
		 * @role characters
		 */
		oracle: "var3",

		/**
		 * @name vesk
		 * @role characters
		 */
		vesk: "var4",

		/**
		 * @name neutral
		 * @role emotions
		 */
		neutral: "var5",

		/**
		 * @name angry
		 * @role emotions
		 */
		angry: "var6",

		/**
		 * @name afraid
		 * @role emotions
		 */
		afraid: "var7",

		/**
		 * @name joy
		 * @role emotions
		 */
		joy: "var8",

		/**
		 * @name suspicious
		 * @role emotions
		 */
		suspicious: "var9",

		/**
		 * @name reactor_deck
		 * @role places
		 */
		reactor_deck: "var10",

		/**
		 * @name docking_ring
		 * @role places
		 */
		docking_ring: "var11",

		/**
		 * @name plasma_cell
		 * @role none
		 */
		plasma_cell: "var12",

		/**
		 * @name keycard
		 * @role none
		 */
		keycard: "var13",

		/**
		 * @name ration
		 * @role none
		 */
		ration: "var14",
	},

	/** Every dictionary id, as ConditionTest.dict cites it. */
	Dictionaries: {
		/**
		 * @type boolean
		 * @entries 5
		 */
		switches: "switches",

		/**
		 * @type number
		 * @entries 4
		 */
		variables: "variables",

		/**
		 * @type number
		 * @entries 3
		 */
		items: "items",

		/**
		 * @type string
		 * @entries 3
		 */
		flags: "flags",
	},

	/** Every entry key, grouped by dictionary: what ConditionTest.entry cites. */
	DictionaryEntries: {
		/**
		 * @dictionary switches
		 * @type boolean
		 */
		switches: {
			door_unlocked: "door_unlocked",
			oracle_awake: "oracle_awake",
			reactor_stable: "reactor_stable",
			met_vesk: "met_vesk",
			alarm_armed: "alarm_armed",
		},

		/**
		 * @dictionary variables
		 * @type number
		 */
		variables: {
			chapter: "chapter",
			credits: "credits",
			trust_kael: "trust_kael",
			alarm_level: "alarm_level",
		},

		/**
		 * @dictionary items
		 * @type number
		 */
		items: {
			plasma_cell: "plasma_cell",
			keycard: "keycard",
			ration: "ration",
		},

		/**
		 * @dictionary flags
		 * @type string
		 */
		flags: {
			faction: "faction",
			last_port: "last_port",
			player_callsign: "player_callsign",
		},
	},

	/** Every engine function id, as ActionCall.fn names it. */
	Functions: {
		/** @params track: string, fadeMs: number, loop: boolean */
		play_music: "play_music",

		/** @params flag: dictionaryKey(switches), value: boolean */
		set_switch: "set_switch",

		/** @params item: dictionaryKey(items), count: number */
		add_item: "add_item",

		/** @params counter: dictionaryKey(variables), value: number */
		set_counter: "set_counter",

		/** @params flag: dictionaryKey(flags), value: string */
		write_flag: "write_flag",

		/** @params intensity: number, durationMs: number */
		shake_camera: "shake_camera",

		/** @params id: string */
		unlock_achievement: "unlock_achievement",

		/** @params (none) */
		close_bulkhead: "close_bulkhead",
	},

	/** Every parameter name, grouped by function: the keys of ActionCall.args. */
	FunctionParams: {
		/** @function play_music */
		play_music: {
			/** @type string */
			track: "track",

			/** @type number */
			fadeMs: "fadeMs",

			/** @type boolean */
			loop: "loop",
		},

		/** @function set_switch */
		set_switch: {
			/** @type dictionaryKey (switches) */
			flag: "flag",

			/** @type boolean */
			value: "value",
		},

		/** @function add_item */
		add_item: {
			/** @type dictionaryKey (items) */
			item: "item",

			/** @type number */
			count: "count",
		},

		/** @function set_counter */
		set_counter: {
			/** @type dictionaryKey (variables) */
			counter: "counter",

			/** @type number */
			value: "value",
		},

		/** @function write_flag */
		write_flag: {
			/** @type dictionaryKey (flags) */
			flag: "flag",

			/** @type string */
			value: "value",
		},

		/** @function shake_camera */
		shake_camera: {
			/** @type number */
			intensity: "intensity",

			/** @type number */
			durationMs: "durationMs",
		},

		/** @function unlock_achievement */
		unlock_achievement: {
			/** @type string */
			id: "id",
		},

		/** @function close_bulkhead */
		close_bulkhead: {
		},
	},
} as const;
